// frontend/src/domains/organizations/views/OrganizationsPage.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import { useOrganizationsQuery } from '../queries/useOrganizationsQuery'
import { usePersonsQuery } from '../../personas/queries/usePersonasQuery'
import OrganizationsList from '../components/OrganizationsList.vue'
import OrganizationsDetail from '../components/OrganizationsDetail.vue'
import type { Organization } from '../types/organization'
import type { EnrichedPerson } from '../../personas/types/persona'
import { ref, computed } from 'vue'

const { t } = useI18n()

const { data: organizationsData, isLoading } = useOrganizationsQuery()
const { data: personsData } = usePersonsQuery()

const selectedOrganizationId = ref('')

const selectedOrganization = computed(() => {
  const orgs = organizationsData.value ?? []
  return orgs.find((o: Organization) => o.organization_id === selectedOrganizationId.value) ?? orgs[0] ?? null
})

const orgPeople = computed(() => {
  const org = selectedOrganization.value
  if (!org) return []
  return (personsData.value ?? []).filter((p: EnrichedPerson) =>
    p.linked_projects?.some((pid: string) =>
      org.display_name && pid.includes(org.display_name)
    )
  ).slice(0, 5)
})
</script>

<template>
  <section class="organizations-page">
    <div class="view-header">
      <div class="view-title-with-icon">
        <span class="hero-mark small"><Icon icon="tabler:building" :size="28" /></span>
        <div>
          <h1>{{ t('Companies') }}</h1>
          <p>{{ t('All companies and organizations from your communications') }}</p>
        </div>
      </div>
    </div>
    <div class="org-layout">
      <OrganizationsList
        :organizations="organizationsData ?? []"
        :selectedOrganizationId="selectedOrganizationId"
        :isOrganizationsLoading="isLoading"
        @selectOrg="(id) => { selectedOrganizationId = id }"
      />
      <OrganizationsDetail
        :selectedOrganization="selectedOrganization as unknown as Record<string, unknown>"
        :orgPeople="orgPeople as unknown as unknown[]"
      />
    </div>
  </section>
</template>

<style scoped>
.organizations-page {
  display: grid;
  grid-template-columns: repeat(var(--hh-layout-columns), minmax(0, 1fr));
  grid-auto-flow: row;
  grid-auto-rows: min-content;
  align-content: start;
  gap: var(--hh-layout-gap);
  height: 100%;
  min-height: 0;
  overflow: hidden;
  padding-right: 0;
}
.organizations-page > * {
  grid-column: 1 / -1;
  min-width: 0;
}
.org-layout {
  display: grid;
  grid-template-columns: 320px 1fr;
  gap: var(--hh-layout-gap);
  min-height: 0;
}
</style>

// frontend/src/lib/pages/organizations/OrganizationsPage.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import { loadOrganizations, loadPersons } from '$lib/services/persons';
	import type { EnrichedPerson, Organization } from '$lib/api';
	import OrganizationsList from './widgets/OrganizationsList.svelte';
	import OrganizationsDetail from './widgets/OrganizationsDetail.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let {
		isLayoutEditing,
		isWidgetVisible
	}: Props = $props();

	let organizations = $state<Organization[]>([]);
	let organizationsError = $state('');
	let isOrganizationsLoading = $state(false);
	let selectedOrganizationId = $state('');
	let persons = $state<EnrichedPerson[]>([]);

	let selectedOrganization = $derived(
		organizations.find((o) => o.organization_id === selectedOrganizationId) ?? organizations[0] ?? null
	);
	let orgPeople = $derived(
		persons.filter((p) =>
			p.linked_projects?.some((pid) =>
				selectedOrganization?.display_name && pid.includes(selectedOrganization.display_name)
			)
		).slice(0, 5)
	);

	$effect(() => {
		isOrganizationsLoading = true;
		loadOrganizations()
			.then((result) => {
				organizations = result.organizations;
				organizationsError = result.error;
				isOrganizationsLoading = false;
			})
			.catch((e: Error) => {
				organizationsError = e.message;
				isOrganizationsLoading = false;
			});

		loadPersons()
			.then((result) => {
				persons = result.persons;
			});
	});
</script>

<section class="organizations-page">
	<div class="view-header"><div class="view-title-with-icon"><span class="hero-mark small"><Icon icon="tabler:building" width="28" height="28" /></span><div><h1>Companies</h1><p>All companies and organizations from your communications</p></div></div></div>
	{#if organizationsError}
		<p class="inline-error">{organizationsError}</p>
	{/if}
	<div class="org-layout">
		<OrganizationsList {organizations} {selectedOrganizationId} {isOrganizationsLoading} {isLayoutEditing} {isWidgetVisible} onSelectOrg={(id) => (selectedOrganizationId = id)} />
		<OrganizationsDetail selectedOrganization={selectedOrganization as Record<string, unknown> | null} orgPeople={orgPeople as unknown[]} {isLayoutEditing} {isWidgetVisible} />
	</div>
</section>
