// frontend/src/domains/notes/views/NotesPage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import { useNotesStore } from '../stores/notes'
import { useNotesQuery } from '../queries/useNotesQuery'
import type { NoteItem } from '../types/notes'
import NotesSourceFilters from '../components/NotesSourceFilters.vue'
import NotesList from '../components/NotesList.vue'
import NotesInsights from '../components/NotesInsights.vue'

const { t } = useI18n()
const store = useNotesStore()

const { data: notesData } = useNotesQuery()

const fallbackNotes: NoteItem[] = [
  { title: 'Welcome to Notes', body: 'This is your personal notes workspace. Notes from connected sources will appear here.', source: 'Hermes Hub', tag: '#reference', time: new Date().toISOString(), icon: 'tabler:notes' },
  { title: 'Meeting Notes Template', body: 'Use this template to capture key decisions, action items, and follow-ups from meetings.', source: 'Hermes Hub', tag: '#meeting', time: new Date().toISOString(), icon: 'tabler:clipboard-list' },
  { title: 'Project Ideas', body: 'A collection of project ideas and brainstorming notes for future development.', source: 'Hermes Hub', tag: '#idea', time: new Date().toISOString(), icon: 'tabler:lightbulb' },
  { title: 'Research Notes', body: 'Research findings and references organized by topic for easy retrieval.', source: 'Hermes Hub', tag: '#research', time: new Date().toISOString(), icon: 'tabler:books' }
]

const notes = computed<NoteItem[]>(() => notesData.value?.items ?? fallbackNotes)
</script>

<template>
  <section class="notes-page">
    <div class="view-header">
      <div class="view-title-with-icon">
        <span class="hero-mark small"><Icon icon="tabler:notes" :size="28" /></span>
        <div>
          <h1>{{ t('Notes') }}</h1>
          <p>{{ t('All your notes from connected sources') }}</p>
        </div>
      </div>
    </div>
    <div class="notes-layout">
      <NotesSourceFilters
        :active-sources="store.activeSources"
        :active-tags="store.activeTags"
        @toggle-source="store.toggleSource"
        @toggle-tag="store.toggleTag"
      />
      <NotesList
        :notes="notes"
        :search-query="store.searchQuery"
        @update:search-query="store.setSearchQuery"
      />
      <aside class="stacked-rail">
        <NotesInsights />
      </aside>
    </div>
  </section>
</template>

// frontend/src/lib/pages/notes/NotesPage.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import NotesSourceFilters from './widgets/NotesSourceFilters.svelte';
	import NotesList from './widgets/NotesList.svelte';
	import NotesInsights from './widgets/NotesInsights.svelte';

	const _ = (key: string) => t($currentLocale, key);

	type Note = { title: string; body: string; source: string; tag: string; time: string; icon: string };

	interface Props {
		notes: Note[];
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { notes, isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<section class="notes-page">
	<div class="view-header">
		<div class="view-title-with-icon"><span class="hero-mark small"><Icon icon="tabler:notes" width="28" height="28" /></span><div><h1>Notes</h1><p>All your notes from connected sources</p></div></div>
	</div>
	<div class="notes-layout">
		<NotesSourceFilters {isLayoutEditing} {isWidgetVisible} />
		<NotesList {notes} {isLayoutEditing} {isWidgetVisible} />
		<aside class="stacked-rail">
			<NotesInsights {isLayoutEditing} {isWidgetVisible} />
		</aside>
	</div>
</section>
