// frontend/src/lib/pages/whatsapp/widgets/WhatsAppMessageThread.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		selectedWhatsappSession: unknown | null;
		selectedWhatsappMessages: unknown[];
		aiAnalysisResult: unknown | null;
		selectedCommunication: unknown | null;
		isWhatsappLoading: boolean;
		isWhatsappActionSubmitting: boolean;
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		whatsappMessageTime: (message: unknown) => string;
		loadWhatsappWebWorkspace: () => Promise<void>;
		ingestWhatsappWebMessageFixture: () => Promise<void>;
		whatsappMessageForm: { provider_message_id: string; sender_display_name: string; text: string };
	}

	let {
		selectedWhatsappSession,
		selectedWhatsappMessages,
		aiAnalysisResult,
		selectedCommunication,
		isWhatsappLoading,
		isWhatsappActionSubmitting,
		isLayoutEditing,
		isWidgetVisible,
		whatsappMessageTime,
		loadWhatsappWebWorkspace,
		ingestWhatsappWebMessageFixture,
		whatsappMessageForm
	}: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="whatsapp-chat-message-surface" data-widget-hidden={!isWidgetVisible('whatsapp-chat-message-surface')}>
	<WidgetEditChrome widgetId="whatsapp-chat-message-surface" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<section class="panel chat-pane whatsapp-chat-pane">
		{#if selectedWhatsappSession}
			{@const session = selectedWhatsappSession as Record<string, unknown>}
			<header>
				<span class="round-icon cyan"><Icon icon="tabler:brand-whatsapp" width="24" height="24" /></span>
				<div><h2>{session.device_name as string}</h2><p>{session.account_id as string} · {session.link_state as string}</p></div>
				<div class="chat-actions">
					<button type="button" disabled title={_('Live WhatsApp Web runtime is blocked in WhatsApp foundation')}><Icon icon="tabler:world" width="17" height="17" /></button>
					<button type="button" disabled title={_('Outbound WhatsApp sends require a future policy and runtime contract')}><Icon icon="tabler:send-off" width="17" height="17" /></button>
					<button type="button" onclick={() => void loadWhatsappWebWorkspace()} disabled={isWhatsappLoading}><Icon icon="tabler:refresh" width="17" height="17" /></button>
				</div>
			</header>
			<div class="chat-body">
				{#if aiAnalysisResult && (aiAnalysisResult as Record<string, unknown>).message_id === (selectedCommunication as { message_id?: string })?.message_id}
					<article class="ai-analysis-card">
						<strong><Icon icon="tabler:sparkles" width="16" height="16" />{_('AI Analysis')}</strong>
						{#if (aiAnalysisResult as Record<string, unknown>).category}<p><em>{_('Category:')}</em> {(aiAnalysisResult as Record<string, unknown>).category as string}</p>{/if}
						{#if (aiAnalysisResult as Record<string, unknown>).summary}<p><em>{_('Summary:')}</em> {(aiAnalysisResult as Record<string, unknown>).summary as string}</p>{/if}
						{#if (aiAnalysisResult as Record<string, unknown>).importance_score != null}<p><em>{_('Importance:')}</em> {(aiAnalysisResult as Record<string, unknown>).importance_score as number}/100</p>{/if}
						<p><em>{_('State:')}</em> <span class="state-badge {(aiAnalysisResult as Record<string, unknown>).workflow_state as string}">{(aiAnalysisResult as Record<string, unknown>).workflow_state as string}</span></p>
					</article>
				{/if}
				{#if selectedWhatsappMessages.length === 0}
					<div class="empty-panel fill">{_('No WhatsApp Web messages for this session.')}</div>
				{:else}
					{#each selectedWhatsappMessages.slice().reverse() as message}
						{@const msg = message as Record<string, unknown>}
						<article class="bubble" class:outbound={msg.delivery_state === 'sent' || msg.delivery_state === 'send_dry_run'} class:inbound={msg.delivery_state !== 'sent' && msg.delivery_state !== 'send_dry_run'}>
							<strong>{(msg.sender_display_name ?? msg.sender) as string}</strong><br />
							{msg.text as string}
							<time>{whatsappMessageTime(message)}</time>
						</article>
					{/each}
				{/if}
			</div>
			<form class="telegram-inline-form" onsubmit={(event) => { event.preventDefault(); void ingestWhatsappWebMessageFixture(); }}>
				<input bind:value={whatsappMessageForm.provider_message_id} placeholder={_('Provider message ID')} autocomplete="off" />
				<input bind:value={whatsappMessageForm.sender_display_name} placeholder={_('Sender')} autocomplete="off" />
				<input bind:value={whatsappMessageForm.text} placeholder={_('Fixture message text')} autocomplete="off" />
				<button type="submit" disabled={isWhatsappActionSubmitting || !whatsappMessageForm.text.trim()}><Icon icon="tabler:send" width="17" height="17" />{_('Ingest')}</button>
			</form>
		{:else}
			<div class="empty-panel fill">{_('Create a WhatsApp Web fixture account before ingesting messages.')}</div>
		{/if}
	</section>
</div>

// frontend/src/integrations/whatsapp/components/WhatsAppMessageThread.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import type { WhatsappWebSession, WhatsappWebMessage } from '../types/whatsapp'
import type { WhatsappMessageForm } from '../stores/whatsapp'

const props = defineProps<{
  selectedWhatsappSession: WhatsappWebSession | null
  selectedWhatsappMessages: WhatsappWebMessage[]
  isWhatsappLoading: boolean
  isWhatsappActionSubmitting: boolean
  whatsappMessageTime: (msg: WhatsappWebMessage) => string
  loadWhatsappWebWorkspace: () => void
  ingestWhatsappWebMessageFixture: () => void
  whatsappMessageForm: WhatsappMessageForm
}>()

const { t } = useI18n()
</script>

<template>
  <section class="panel chat-pane whatsapp-chat-pane">
    <template v-if="selectedWhatsappSession">
      <header>
        <span class="round-icon cyan">
          <Icon icon="tabler:brand-whatsapp" width="24" height="24" />
        </span>
        <div>
          <h2>{{ selectedWhatsappSession.device_name }}</h2>
          <p>{{ selectedWhatsappSession.account_id }} · {{ selectedWhatsappSession.link_state }}</p>
        </div>
      </header>

      <div class="message-scroll">
        <article
          v-for="msg in selectedWhatsappMessages"
          :key="msg.message_id"
          class="message-bubble"
        >
          <strong>{{ msg.sender_display_name ?? msg.sender }}</strong>
          <p>{{ msg.text }}</p>
          <time>{{ whatsappMessageTime(msg) }}</time>
        </article>
        <div v-if="selectedWhatsappMessages.length === 0" class="empty-panel">
          {{ t('No messages for this session.') }}
        </div>
      </div>

      <form class="telegram-inline-form" @submit.prevent="ingestWhatsappWebMessageFixture">
        <input
          v-model="whatsappMessageForm.provider_message_id"
          :placeholder="t('Provider message ID')"
          autocomplete="off"
        />
        <input
          v-model="whatsappMessageForm.sender_display_name"
          :placeholder="t('Sender')"
          autocomplete="off"
        />
        <input
          v-model="whatsappMessageForm.text"
          :placeholder="t('Fixture message text')"
          autocomplete="off"
        />
        <button
          type="submit"
          :disabled="isWhatsappActionSubmitting || !whatsappMessageForm.text.trim()"
        >
          <Icon icon="tabler:send" width="17" height="17" />{{ t('Ingest') }}
        </button>
      </form>
    </template>

    <div v-else class="empty-panel">
      {{ t('No WhatsApp session selected.') }}
    </div>
  </section>
</template>

<style scoped>
.chat-pane {
  display: flex;
  flex-direction: column;
  height: 100%;
}
.message-scroll {
  flex: 1;
  overflow-y: auto;
  padding: 0.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}
.message-bubble {
  background: var(--bg-card);
  border-radius: var(--radius-sm);
  padding: 0.5rem 0.75rem;
  max-width: 85%;
}
.message-bubble strong {
  display: block;
  font-size: 0.75rem;
  color: var(--accent);
  margin-bottom: 0.2rem;
}
.message-bubble p {
  margin: 0;
  font-size: 0.875rem;
}
.message-bubble time {
  display: block;
  font-size: 0.7rem;
  color: var(--text-secondary);
  margin-top: 0.25rem;
}
.telegram-inline-form {
  display: flex;
  gap: 0.4rem;
  padding: 0.5rem;
  border-top: 1px solid var(--border);
  flex-wrap: wrap;
}
.telegram-inline-form input {
  flex: 1;
  min-width: 100px;
  padding: 0.35rem 0.5rem;
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  background: var(--bg-input);
  color: var(--text-primary);
  font-size: 0.8rem;
}
.telegram-inline-form button {
  display: inline-flex;
  align-items: center;
  gap: 0.2rem;
  padding: 0.35rem 0.75rem;
  border: none;
  border-radius: var(--radius-sm);
  background: var(--accent);
  color: var(--accent-fg);
  cursor: pointer;
  font-size: 0.8rem;
}
.telegram-inline-form button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
