// frontend/src/domains/notes/components/NotesInsights.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'

const { t } = useI18n()
</script>

<template>
  <div class="widget-frame">
    <section class="panel info-card">
      <h2>{{ t('Note Insights') }}</h2>
      <p>{{ t('AI generated summaries and connections across your notes will appear here.') }}</p>
    </section>
  </div>
</template>

// frontend/src/lib/pages/notes/widgets/NotesInsights.svelte
<script lang="ts">
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="notes-insights" data-widget-hidden={!isWidgetVisible('notes-insights')}>
	<WidgetEditChrome widgetId="notes-insights" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<section class="panel info-card">
		<h2>Note Insights</h2>
		<p>AI generated summaries and connections across your notes will appear here.</p>
	</section>
</div>
