// frontend/src/domains/notes/components/NotesSourceFilters.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'

const { t } = useI18n()

defineProps<{
  activeSources: string[]
  activeTags: string[]
}>()

const emit = defineEmits<{
  'toggle-source': [source: string]
  'toggle-tag': [tag: string]
}>()

const sources = ['Apple Notes', 'Obsidian', 'Gmail', 'Anytype', 'Outlook']
const tags = ['#project', '#research', '#meeting', '#idea', '#reference', '#partnership']
</script>

<template>
  <aside class="left-panels">
    <div class="widget-frame">
      <section class="panel info-card">
        <h2>{{ t('Sources') }}</h2>
        <label v-for="src in sources" :key="src" class="mini-check">
          <input
            type="checkbox"
            :checked="activeSources.includes(src)"
            @change="emit('toggle-source', src)"
          />
          {{ t(src) }}
        </label>
      </section>
    </div>
    <div class="widget-frame">
      <section class="panel info-card">
        <h2>{{ t('Tags') }}</h2>
        <label v-for="tag in tags" :key="tag" class="mini-check">
          <input
            type="checkbox"
            :checked="activeTags.includes(tag)"
            @change="emit('toggle-tag', tag)"
          />
          {{ t(tag) }}
        </label>
      </section>
    </div>
  </aside>
</template>

// frontend/src/lib/pages/notes/widgets/NotesSourceFilters.svelte
<script lang="ts">
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<aside class="left-panels">
	<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="notes-source-filters" data-widget-hidden={!isWidgetVisible('notes-source-filters')}>
		<WidgetEditChrome widgetId="notes-source-filters" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
		<section class="panel info-card">
			<h2>{_('Sources')}</h2>
			{#each ['Apple Notes','Obsidian','Gmail','Anytype','Outlook'] as source}
				<label class="mini-check"><input type="checkbox" checked />{_(source)}</label>
			{/each}
		</section>
	</div>
	<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="notes-tags" data-widget-hidden={!isWidgetVisible('notes-tags')}>
		<WidgetEditChrome widgetId="notes-tags" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
		<section class="panel info-card">
			<h2>{_('Tags')}</h2>
			{#each ['#project','#research','#meeting','#idea','#reference','#partnership'] as tag}
				<label class="mini-check"><input type="checkbox" checked />{_(tag)}</label>
			{/each}
		</section>
	</div>
</aside>
