// frontend/src/domains/whatsapp/views/WhatsAppPage.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'

// Components
import WhatsAppSessionList from '../components/WhatsAppSessionList.vue'
import WhatsAppMessageThread from '../components/WhatsAppMessageThread.vue'
import WhatsAppRail from '../components/WhatsAppRail.vue'
import WhatsAppStatusMessages from '../components/WhatsAppStatusMessages.vue'

// Store
import { useWhatsappStore } from '../stores/whatsapp'

// API
import * as whatsappApi from '../api/whatsapp'

// TanStack Query
import { useWhatsappCapabilitiesQuery } from '../queries/useWhatsappQuery'

const { t } = useI18n()
const store = useWhatsappStore()

// Capabilities query
const { data: capabilities } = useWhatsappCapabilitiesQuery()

onMounted(() => {
  void loadWhatsappWebWorkspace()
})

async function loadWhatsappWebWorkspace() {
  store.setWhatsappLoading(true)
  try {
    const result = await whatsappApi.loadWhatsappWebWorkspace(
      store.selectedWhatsappSessionId
    )
    store.setWhatsappData(result)
  } catch (err) {
    store.setWhatsappError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setWhatsappLoading(false)
  }
}

function selectWhatsappSession(session: any) {
  store.selectWhatsappSession(session)
  void loadWhatsappWebWorkspace()
}

async function ingestWhatsappWebMessageFixture() {
  if (store.isWhatsappActionSubmitting) return
  store.setWhatsappActionSubmitting(true)
  store.setWhatsappActionMessage('')
  store.setWhatsappError('')
  try {
    const result = await whatsappApi.ingestWhatsappWebMessageFixture({
      account_id: store.whatsappMessageForm.account_id,
      provider_chat_id: store.whatsappMessageForm.provider_chat_id,
      provider_message_id: store.whatsappMessageForm.provider_message_id,
      chat_title: store.whatsappMessageForm.chat_title,
      sender_id: store.whatsappMessageForm.sender_id,
      sender_display_name: store.whatsappMessageForm.sender_display_name,
      text: store.whatsappMessageForm.text,
      import_batch_id: store.whatsappMessageForm.import_batch_id,
      occurred_at: store.whatsappMessageForm.occurred_at,
      delivery_state: store.whatsappMessageForm.delivery_state
    })
    if (result.error) {
      store.setWhatsappError(result.error)
    } else {
      store.setWhatsappActionMessage(result.message)
      store.whatsappMessageForm = {
        ...store.whatsappMessageForm,
        provider_message_id: result.nextProviderMessageId,
        occurred_at: result.nextOccurredAt
      }
      await loadWhatsappWebWorkspace()
    }
  } catch (err) {
    store.setWhatsappError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setWhatsappActionSubmitting(false)
  }
}

function openAccountDrawer() {
  // Placeholder — account wizard integration TBD
  store.setWhatsappActionMessage(t('Account wizard integration pending.'))
}
</script>

<template>
  <section class="whatsapp-page communications-page">
    <div class="view-header">
      <div class="view-title-with-icon">
        <span class="hero-mark small">
          <Icon icon="tabler:brand-whatsapp" width="28" height="28" />
        </span>
        <div>
          <h1>{{ t('WhatsApp') }}</h1>
          <p>{{ t('WhatsApp Web sessions and messages') }}</p>
        </div>
      </div>
      <button
        type="button"
        class="primary-button"
        @click="openAccountDrawer"
      >
        <Icon icon="tabler:plus" width="16" height="16" />{{ t('Add Account') }}
      </button>
      <button
        type="button"
        class="primary-button"
        :disabled="store.isWhatsappLoading"
        @click="loadWhatsappWebWorkspace"
      >
        <Icon icon="tabler:refresh" width="16" height="16" />{{ t('Refresh') }}
      </button>
    </div>

    <div class="metric-grid">
      <article class="metric-card">
        <span>{{ t('Sessions') }}</span>
        <strong>{{ store.whatsappSessions.length }}</strong>
        <small>{{ store.selectedWhatsappSession?.link_state ?? t('not linked') }}</small>
      </article>
      <article class="metric-card">
        <span>{{ t('Messages') }}</span>
        <strong>{{ store.whatsappMessages.length }}</strong>
        <small>{{ t('Canonical WhatsApp Web records') }}</small>
      </article>
      <article class="metric-card">
        <span>{{ t('Runtime') }}</span>
        <strong>{{ capabilities?.runtime_mode ?? t('unknown') }}</strong>
        <small>{{ t('Fixture/manual foundation') }}</small>
      </article>
      <article class="metric-card">
        <span>{{ t('Blocked') }}</span>
        <strong>{{ store.whatsappBlockedCapabilities.length }}</strong>
        <small>{{ t('Live runtime remains blocked') }}</small>
      </article>
    </div>

    <WhatsAppStatusMessages
      :action-message="store.whatsappActionMessage"
      :error="store.whatsappError"
    />

    <div class="three-pane communications-grid whatsapp-grid">
      <WhatsAppSessionList
        :whatsapp-sessions="store.whatsappSessions"
        :selected-whatsapp-session-id="store.selectedWhatsappSessionId"
        :is-whatsapp-loading="store.isWhatsappLoading"
        @select-session="selectWhatsappSession"
      />

      <WhatsAppMessageThread
        :selected-whatsapp-session="store.selectedWhatsappSession"
        :selected-whatsapp-messages="store.selectedWhatsappMessages"
        :is-whatsapp-loading="store.isWhatsappLoading"
        :is-whatsapp-action-submitting="store.isWhatsappActionSubmitting"
        :whatsapp-message-time="whatsappApi.whatsappMessageTime"
        :load-whatsapp-web-workspace="loadWhatsappWebWorkspace"
        :ingest-whatsapp-web-message-fixture="ingestWhatsappWebMessageFixture"
        :whatsapp-message-form="store.whatsappMessageForm"
      />

      <WhatsAppRail
        :whatsapp-capabilities="store.whatsappCapabilities"
        :whatsapp-closure-capabilities="store.whatsappClosureCapabilities"
        :whatsapp-blocked-capabilities="store.whatsappBlockedCapabilities"
        :whatsapp-provider-accounts="0"
        :is-whatsapp-action-submitting="store.isWhatsappActionSubmitting"
        :open-account-drawer="openAccountDrawer"
        :ingest-whatsapp-web-message-fixture="ingestWhatsappWebMessageFixture"
        :whatsapp-message-form="store.whatsappMessageForm"
      />
    </div>
  </section>
</template>

// frontend/src/lib/pages/whatsapp/WhatsAppPage.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';
	import WhatsAppSessionList from './widgets/WhatsAppSessionList.svelte';
	import WhatsAppMessageThread from './widgets/WhatsAppMessageThread.svelte';
	import WhatsAppRail from './widgets/WhatsAppRail.svelte';
	import * as whatsappService from '$lib/services/whatsapp';
	import * as formattingService from '$lib/services/formatting';
	import { openAccountDrawer } from '$lib/stores/accountWizard';
	import { whatsappProviderAccounts } from '$lib/stores/settings';
	import type {
		WhatsappWebSession,
		WhatsappWebMessage,
		WhatsappCapabilitiesResponse,
		WhatsappCapabilityStatus,
		MessageAnalyzeResponse
	} from '$lib/api';

	const _ = (key: string) => t($currentLocale, key);

	interface WhatsappMessageForm {
		account_id: string;
		provider_chat_id: string;
		provider_message_id: string;
		chat_title: string;
		sender_id: string;
		sender_display_name: string;
		text: string;
		import_batch_id: string;
		occurred_at: string;
		delivery_state: string;
	}

	let whatsappSessions = $state<WhatsappWebSession[]>([]);
	let whatsappMessages = $state<WhatsappWebMessage[]>([]);
	let whatsappCapabilities = $state<WhatsappCapabilitiesResponse | null>(null);
	let selectedWhatsappSessionId = $state('');
	let whatsappError = $state('');
	let whatsappActionMessage = $state('');
	let isWhatsappLoading = $state(false);
	let isWhatsappActionSubmitting = $state(false);

	let whatsappMessageForm = $state<WhatsappMessageForm>({
		account_id: 'whatsapp-primary',
		provider_chat_id: 'wa-fixture-chat-1',
		provider_message_id: 'wa-fixture-msg-1',
		chat_title: 'WhatsApp Planning',
		sender_id: 'wa-fixture-user',
		sender_display_name: 'WhatsApp Fixture',
		text: 'WhatsApp fixture WhatsApp Web message for local memory and graph recall.',
		import_batch_id: 'whatsapp-web-fixture-ui',
		occurred_at: new Date().toISOString(),
		delivery_state: 'received'
	});

	const selectedWhatsappSession = $derived(
		whatsappSessions.find((session) => session.session_id === selectedWhatsappSessionId) ??
			whatsappSessions[0] ??
			null
	);
	const selectedWhatsappMessages = $derived(
		selectedWhatsappSession
			? whatsappMessages.filter((message) => message.account_id === selectedWhatsappSession.account_id)
			: whatsappMessages
	);
	const whatsappClosureCapabilities = $derived(
		whatsappCapabilities?.capabilities.filter((capability) => capability.closure_gate) ?? []
	);
	const whatsappBlockedCapabilities = $derived(
		whatsappCapabilities?.capabilities.filter((capability) => capability.status === 'blocked') ?? []
	);

	const formatDateTime = formattingService.formatDateTime;
	const whatsappMessageTime = whatsappService.whatsappMessageTime;

	function capabilityLabel(capability: string) {
		return capability
			.split('_')
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join(' ');
	}

	function openAccountWizard(target: string) {
		openAccountDrawer(target as Parameters<typeof openAccountDrawer>[0]);
	}

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		aiAnalysisResult: MessageAnalyzeResponse | null;
		selectedCommunication: unknown;
	}

	let {
		isLayoutEditing,
		isWidgetVisible,
		aiAnalysisResult,
		selectedCommunication
	}: Props = $props();

	onMount(() => {
		void loadWhatsappWebWorkspace();
	});

	async function loadWhatsappWebWorkspace() {
		isWhatsappLoading = true;
		const result = await whatsappService.loadWhatsappWebWorkspace(selectedWhatsappSessionId);
		whatsappCapabilities = result.capabilities;
		whatsappSessions = result.sessions;
		whatsappMessages = result.messages;
		selectedWhatsappSessionId = result.selectedSessionId;
		whatsappError = result.error;
		isWhatsappLoading = false;
	}

	function selectWhatsappSession(session: WhatsappWebSession) {
		selectedWhatsappSessionId = session.session_id;
		whatsappMessageForm = {
			...whatsappMessageForm,
			account_id: session.account_id
		};
	}

	async function ingestWhatsappWebMessageFixture() {
		if (isWhatsappActionSubmitting) return;
		isWhatsappActionSubmitting = true;
		whatsappActionMessage = '';
		whatsappError = '';
		const result = await whatsappService.ingestWhatsappWebMessageFixture({
			account_id: whatsappMessageForm.account_id,
			provider_chat_id: whatsappMessageForm.provider_chat_id,
			provider_message_id: whatsappMessageForm.provider_message_id,
			chat_title: whatsappMessageForm.chat_title,
			sender_id: whatsappMessageForm.sender_id,
			sender_display_name: whatsappMessageForm.sender_display_name,
			text: whatsappMessageForm.text,
			import_batch_id: whatsappMessageForm.import_batch_id,
			occurred_at: whatsappMessageForm.occurred_at,
			delivery_state: whatsappMessageForm.delivery_state
		});
		if (result.error) {
			whatsappError = result.error;
		} else {
			whatsappActionMessage = result.message;
			whatsappMessageForm = {
				...whatsappMessageForm,
				provider_message_id: result.nextProviderMessageId,
				occurred_at: result.nextOccurredAt
			};
			await loadWhatsappWebWorkspace();
		}
		isWhatsappActionSubmitting = false;
	}
</script>

<section class="whatsapp-page communications-page">
	<div class="view-header">
		<div class="view-title-with-icon"><span class="hero-mark small"><Icon icon="tabler:brand-whatsapp" width="28" height="28" /></span><div><h1>{_('WhatsApp')}</h1><p>{_('WhatsApp Web sessions and messages')}</p></div></div>
		<button type="button" class="primary-button" onclick={() => openAccountDrawer('whatsapp')}><Icon icon="tabler:plus" width="16" height="16" />{_('Add Account')}</button>
		<button type="button" class="primary-button" onclick={() => void loadWhatsappWebWorkspace()} disabled={isWhatsappLoading}><Icon icon="tabler:refresh" width="16" height="16" />{_('Refresh')}</button>
	</div>

	<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="whatsapp-session-status" data-widget-hidden={!isWidgetVisible('whatsapp-session-status')}>
		<WidgetEditChrome widgetId="whatsapp-session-status" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
		<div class="metric-grid">
			<article class="metric-card"><span>{_('Sessions')}</span><strong>{whatsappSessions.length}</strong><small>{selectedWhatsappSession?.link_state ?? _('not linked')}</small></article>
			<article class="metric-card"><span>{_('Messages')}</span><strong>{whatsappMessages.length}</strong><small>{_('Canonical WhatsApp Web records')}</small></article>
			<article class="metric-card"><span>{_('Runtime')}</span><strong>{whatsappCapabilities?.runtime_mode ?? _('unknown')}</strong><small>{_('Fixture/manual foundation')}</small></article>
			<article class="metric-card"><span>{_('Blocked')}</span><strong>{whatsappBlockedCapabilities.length}</strong><small>{_('Live runtime remains blocked')}</small></article>
		</div>
	</div>

	{#if whatsappActionMessage}
		<p class="setup-state success">{whatsappActionMessage}</p>
	{/if}
	{#if whatsappError}
		<p class="inline-error">{whatsappError}</p>
	{/if}

	<div class="three-pane communications-grid whatsapp-grid">
		<WhatsAppSessionList
			whatsappSessions={whatsappSessions as unknown[]}
			selectedWhatsappSessionId={selectedWhatsappSession?.session_id ?? ''}
			{isWhatsappLoading}
			{isLayoutEditing}
			{isWidgetVisible}
			onSelectSession={selectWhatsappSession as unknown as (session: unknown) => void}
			{formatDateTime}
		/>
		<WhatsAppMessageThread
			selectedWhatsappSession={selectedWhatsappSession as unknown | null}
			selectedWhatsappMessages={selectedWhatsappMessages as unknown[]}
			{aiAnalysisResult}
			{selectedCommunication}
			{isWhatsappLoading}
			{isWhatsappActionSubmitting}
			{isLayoutEditing}
			{isWidgetVisible}
			whatsappMessageTime={whatsappMessageTime as unknown as (msg: unknown) => string}
			{loadWhatsappWebWorkspace}
			{ingestWhatsappWebMessageFixture}
			whatsappMessageForm={whatsappMessageForm as unknown as { provider_message_id: string; sender_display_name: string; text: string; account_id: string; provider_chat_id: string; chat_title: string; sender_id: string }}
		/>
		<WhatsAppRail
			whatsappClosureCapabilities={whatsappClosureCapabilities as unknown[]}
			whatsappBlockedCapabilities={whatsappBlockedCapabilities as unknown[]}
			{whatsappCapabilities}
			whatsappProviderAccounts={$whatsappProviderAccounts as unknown[]}
			{isWhatsappActionSubmitting}
			{isLayoutEditing}
			{isWidgetVisible}
			{capabilityLabel}
			openAccountDrawer={openAccountWizard}
			{ingestWhatsappWebMessageFixture}
			whatsappMessageForm={whatsappMessageForm as unknown as { provider_message_id: string; sender_display_name: string; text: string; account_id: string; provider_chat_id: string; chat_title: string; sender_id: string }}
		/>
	</div>

</section>
