// frontend/src/lib/pages/telegram/TelegramPage.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { currentLocale, t } from '$lib/i18n';
	import TelegramActionRail from './widgets/TelegramActionRail.svelte';
	import TelegramChatList from './widgets/TelegramChatList.svelte';
	import TelegramCommandHeader from './widgets/TelegramCommandHeader.svelte';
	import TelegramMessageThread from './widgets/TelegramMessageThread.svelte';
	import TelegramRail from './widgets/TelegramRail.svelte';
	import TelegramStatusMessages from './widgets/TelegramStatusMessages.svelte';
	import * as telegramService from '$lib/services/telegram';
	import * as formattingService from '$lib/services/formatting';
	import { openAccountDrawer } from '$lib/stores/accountWizard';
	import { runNewWorkflowAction } from '$lib/stores/communications';
	import type {
		TelegramChat,
		TelegramMessage,
		TelegramCapabilitiesResponse,
		TelegramRuntimeStatus,
		MessageAnalyzeResponse
	} from '$lib/api';
	import type {
		TelegramChatFilter,
		TelegramChatGroupFilter,
		TelegramAttachmentHint,
		TelegramRailTab,
		TelegramThreadTab
	} from '$lib/services/telegram';

	const _ = (key: string) => t($currentLocale, key);

	interface TelegramManualSendForm {
		text: string;
	}

	let telegramChats = $state<TelegramChat[]>([]);
	let telegramMessages = $state<TelegramMessage[]>([]);
	let telegramCapabilities = $state<TelegramCapabilitiesResponse | null>(null);
	let telegramRuntimeStatuses = $state<Record<string, TelegramRuntimeStatus>>({});
	let selectedTelegramChatId = $state('');
	let telegramError = $state('');
	let telegramActionMessage = $state('');
	let isTelegramLoading = $state(false);
	let isTelegramActionSubmitting = $state(false);
	let isTelegramHistorySyncing = $state(false);
	let telegramSearchQuery = $state('');
	let activeTelegramFilter = $state<TelegramChatFilter>('all');
	let activeTelegramGroupFilter = $state('local:all');
	let activeThreadTab = $state<TelegramThreadTab>('messages');
	let activeRailTab = $state<TelegramRailTab>('context');
	let isTelegramFiltersMenuOpen = $state(false);
	let isTelegramNewMenuOpen = $state(false);
	let isTelegramInspectorOpen = $state(false);
	const telegramAutoHistorySyncKeys = new Set<string>();

	let telegramManualSendForm = $state<TelegramManualSendForm>({
		text: ''
	});

	const selectedTelegramChat = $derived(
		telegramChats.find((chat) => chat.provider_chat_id === selectedTelegramChatId) ??
			telegramChats[0] ??
			null
	);
	const selectedTelegramMessages = $derived(
		selectedTelegramChat
			? telegramService.telegramMessagesChronological(
					telegramMessages.filter(
						(message) => message.provider_chat_id === selectedTelegramChat.provider_chat_id
					)
				)
			: telegramMessages
	);
	const telegramChatFilterCounts = $derived(
		telegramService.telegramChatFilterCounts(telegramChats, telegramMessages)
	);
	const telegramChatGroupFilters = $derived(
		telegramService.telegramChatGroupFilters(telegramChats)
	);
	const filteredTelegramChats = $derived(
		telegramService.filterTelegramChats(
			telegramService.filterTelegramChatsByGroup(telegramChats, activeTelegramGroupFilter),
			telegramMessages,
			telegramSearchQuery,
			activeTelegramFilter
		)
	);
	const selectedTelegramRuntimeStatus = $derived(
		selectedTelegramChat ? telegramRuntimeStatuses[selectedTelegramChat.account_id] ?? null : null
	);
	const isTelegramBusy = $derived(isTelegramActionSubmitting || isTelegramHistorySyncing);
	const telegramRuntimeLabel = $derived(
		selectedTelegramRuntimeStatus?.status ?? telegramCapabilities?.runtime_mode ?? _('Runtime Status')
	);

	const formatDateTime = formattingService.formatDateTime;
	const telegramMessageTime = telegramService.telegramMessageTime;
	const telegramFilterTabs: Array<{ id: TelegramChatFilter; label: string }> = [
		{ id: 'all', label: 'All Chats' },
		{ id: 'unread', label: 'Unread' },
		{ id: 'mentions', label: 'Mentions' },
		{ id: 'pinned', label: 'Pinned' },
		{ id: 'projects', label: 'Projects' },
		{ id: 'bots', label: 'Bots' },
		{ id: 'archived', label: 'Archived' }
	];

	function closeTelegramMenus() {
		isTelegramFiltersMenuOpen = false;
		isTelegramNewMenuOpen = false;
	}

	function toggleTelegramFiltersMenu() {
		isTelegramFiltersMenuOpen = !isTelegramFiltersMenuOpen;
		isTelegramNewMenuOpen = false;
	}

	function toggleTelegramNewMenu() {
		isTelegramNewMenuOpen = !isTelegramNewMenuOpen;
		isTelegramFiltersMenuOpen = false;
	}

	function selectTelegramFilter(filter: TelegramChatFilter) {
		activeTelegramFilter = filter;
		closeTelegramMenus();
	}

	function selectTelegramGroupFilter(filter: TelegramChatGroupFilter) {
		activeTelegramGroupFilter = filter.id;
		closeTelegramMenus();
	}

	function openTelegramInspector(tab: TelegramRailTab = activeRailTab) {
		activeRailTab = tab;
		isTelegramInspectorOpen = true;
	}

	function closeTelegramInspector() {
		isTelegramInspectorOpen = false;
	}

	function openTelegramNewMessage() {
		closeTelegramMenus();
		activeThreadTab = 'messages';
		if (!selectedTelegramChat) {
			telegramActionMessage = _('Select a synced Telegram chat before composing.');
			return;
		}
		telegramManualSendForm = { text: '' };
		telegramActionMessage = `${_('Manual send target')}: ${selectedTelegramChat.title}`;
	}

	async function runTelegramQuickAction(
		action: 'create_note' | 'create_task' | 'create_contact' | 'create_document'
	) {
		closeTelegramMenus();
		await runNewWorkflowAction(action);
	}

	function openTelegramAccountSetup() {
		openAccountDrawer('telegram');
	}

	function toggleTelegramInspector() {
		isTelegramInspectorOpen ? closeTelegramInspector() : openTelegramInspector();
	}

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		aiAnalysisResult: MessageAnalyzeResponse | null;
		selectedCommunication: unknown;
	}

	let {
		isLayoutEditing,
		isWidgetVisible,
		aiAnalysisResult,
		selectedCommunication
	}: Props = $props();

	onMount(() => {
		void loadTelegramWorkspace();
	});

	async function loadTelegramWorkspace() {
		isTelegramLoading = true;
		const result = await telegramService.loadTelegramWorkspace(selectedTelegramChatId, '');
		telegramCapabilities = result.capabilities;
		telegramChats = result.chats;
		telegramMessages = result.messages;
		telegramRuntimeStatuses = result.runtimeStatuses;
		selectedTelegramChatId = result.selectedChatId;
		telegramError = result.error;
		isTelegramLoading = false;
		if (!telegramService.telegramChatGroupFilters(telegramChats).some((group) => group.id === activeTelegramGroupFilter)) {
			activeTelegramGroupFilter = 'local:all';
		}
		const nextSelectedChat = telegramChats.find((chat) => chat.provider_chat_id === selectedTelegramChatId) ?? null;
		void autoSyncTelegramHistory(nextSelectedChat);
	}

	function selectTelegramChat(chat: TelegramChat) {
		selectedTelegramChatId = chat.provider_chat_id;
		activeThreadTab = 'messages';
		activeRailTab = 'context';
		void loadTelegramWorkspace();
	}

	async function startTelegramRuntime() {
		if (isTelegramBusy || !selectedTelegramChat) return;
		isTelegramActionSubmitting = true;
		telegramActionMessage = '';
		telegramError = '';
		const result = await telegramService.startTelegramRuntimeFromUi(selectedTelegramChat.account_id);
		if (result.error) {
			telegramError = result.error;
		} else if (result.status) {
			telegramRuntimeStatuses = {
				...telegramRuntimeStatuses,
				[result.status.account_id]: result.status
			};
			telegramActionMessage = result.message;
		}
		isTelegramActionSubmitting = false;
	}

	async function syncTelegramChats() {
		if (isTelegramBusy || !selectedTelegramChat) return;
		isTelegramActionSubmitting = true;
		telegramActionMessage = '';
		telegramError = '';
		const result = await telegramService.syncTelegramChatsFromUi(selectedTelegramChat.account_id);
		if (result.error) {
			telegramError = result.error;
		} else {
			telegramActionMessage = result.message;
			await loadTelegramWorkspace();
		}
		isTelegramActionSubmitting = false;
	}

	async function syncSelectedTelegramHistory() {
		if (isTelegramBusy || !selectedTelegramChat) return;
		isTelegramActionSubmitting = true;
		telegramActionMessage = '';
		telegramError = '';
		const result = await telegramService.syncTelegramSelectedHistoryFromUi({
			account_id: selectedTelegramChat.account_id,
			provider_chat_id: selectedTelegramChat.provider_chat_id,
			chat_kind: selectedTelegramChat.chat_kind
		});
		if (result.error) {
			telegramError = result.error;
		} else {
			selectedTelegramChatId = result.providerChatId;
			telegramActionMessage = result.message;
			await loadTelegramWorkspace();
		}
		isTelegramActionSubmitting = false;
	}

	async function autoSyncTelegramHistory(chat: TelegramChat | null) {
		if (!chat || isTelegramBusy) return;
		const syncKey = telegramHistorySyncKey(chat);
		if (telegramAutoHistorySyncKeys.has(syncKey)) return;
		if (chat.chat_kind !== 'private' && hasProjectedMessagesForTelegramChat(chat)) return;

		telegramAutoHistorySyncKeys.add(syncKey);
		isTelegramHistorySyncing = true;
		telegramError = '';
		try {
			const result = await telegramService.syncTelegramSelectedHistoryFromUi({
				account_id: chat.account_id,
				provider_chat_id: chat.provider_chat_id,
				chat_kind: chat.chat_kind
			});
			if (result.error) {
				telegramAutoHistorySyncKeys.delete(syncKey);
				telegramError = result.error;
			} else {
				telegramActionMessage = result.message;
				await loadTelegramWorkspace();
			}
		} finally {
			isTelegramHistorySyncing = false;
		}
	}

	function hasProjectedMessagesForTelegramChat(chat: TelegramChat) {
		return telegramMessages.some(
			(message) =>
				message.account_id === chat.account_id &&
				message.provider_chat_id === chat.provider_chat_id
		);
	}

	function telegramHistorySyncKey(chat: TelegramChat) {
		return `${chat.account_id}:${chat.provider_chat_id}`;
	}

	async function syncOlderTelegramHistory() {
		if (isTelegramBusy || !selectedTelegramChat) return;
		const fromMessageId = telegramService.telegramOldestTdlibMessageId(selectedTelegramMessages);
		if (fromMessageId === null) {
			await autoSyncTelegramHistory(selectedTelegramChat);
			return;
		}

		isTelegramHistorySyncing = true;
		telegramError = '';
		try {
			const result = await telegramService.syncTelegramOlderHistoryFromUi({
				account_id: selectedTelegramChat.account_id,
				provider_chat_id: selectedTelegramChat.provider_chat_id,
				from_message_id: fromMessageId
			});
			if (result.error) {
				telegramError = result.error;
			} else {
				telegramActionMessage = result.hasMore
					? result.message
					: `${result.message}; ${_('no older Telegram messages')}`;
				await loadTelegramWorkspace();
			}
		} finally {
			isTelegramHistorySyncing = false;
		}
	}

	async function sendTelegramManualMessage() {
		if (isTelegramBusy || !selectedTelegramChat) return;
		isTelegramActionSubmitting = true;
		telegramActionMessage = '';
		telegramError = '';
		const result = await telegramService.sendTelegramManualMessageFromUi({
			account_id: selectedTelegramChat.account_id,
			provider_chat_id: selectedTelegramChat.provider_chat_id,
			text: telegramManualSendForm.text
		});
		if (result.error) {
			telegramError = result.error;
		} else {
			selectedTelegramChatId = result.providerChatId;
			telegramActionMessage = result.message;
			telegramManualSendForm = { text: result.nextText };
			await loadTelegramWorkspace();
		}
		isTelegramActionSubmitting = false;
	}

	async function downloadTelegramMedia(attachment: TelegramAttachmentHint, message?: TelegramMessage) {
		if (isTelegramBusy) return;
		if (!selectedTelegramChat) {
			telegramActionMessage = '';
			telegramError = _('Select a Telegram chat before downloading media.');
			return;
		}
		if (attachment.tdlibFileId === null) {
			telegramActionMessage = '';
			telegramError = _('Telegram attachment does not include TDLib file metadata.');
			return;
		}
		const sourceMessage =
			message ??
			selectedTelegramMessages.find((item) => item.message_id === attachment.messageId) ??
			null;
		if (!sourceMessage) {
			telegramActionMessage = '';
			telegramError = _('Telegram source message is not available for this attachment.');
			return;
		}

		isTelegramActionSubmitting = true;
		telegramActionMessage = '';
		telegramError = '';
		const result = await telegramService.downloadTelegramMediaFromUi({
			account_id: sourceMessage.account_id,
			provider_chat_id: sourceMessage.provider_chat_id || selectedTelegramChat.provider_chat_id,
			provider_message_id: sourceMessage.provider_message_id,
			tdlib_file_id: attachment.tdlibFileId,
			provider_attachment_id: attachment.providerAttachmentId,
			filename: attachment.fileName,
			content_type: attachment.mimeType ?? undefined,
			priority: 16
		});
		if (result.error) {
			telegramError = result.error;
		} else {
			telegramActionMessage = result.message;
			await loadTelegramWorkspace();
		}
		isTelegramActionSubmitting = false;
	}

</script>

<section class="telegram-page communications-page">
	<TelegramCommandHeader
		bind:searchQuery={telegramSearchQuery}
		runtimeLabel={telegramRuntimeLabel}
		filterTabs={telegramFilterTabs}
		filterCounts={telegramChatFilterCounts}
		activeFilter={activeTelegramFilter}
		isFiltersMenuOpen={isTelegramFiltersMenuOpen}
		isNewMenuOpen={isTelegramNewMenuOpen}
		{isTelegramBusy}
		{selectedTelegramChat}
		onToggleFiltersMenu={toggleTelegramFiltersMenu}
		onToggleNewMenu={toggleTelegramNewMenu}
		onSelectFilter={selectTelegramFilter}
		onSyncChats={() => { closeTelegramMenus(); void syncTelegramChats(); }}
		onAddAccount={openTelegramAccountSetup}
		onNewMessage={openTelegramNewMessage}
		onQuickAction={(action) => void runTelegramQuickAction(action)}
	/>

	<TelegramActionRail
		groupFilters={telegramChatGroupFilters}
		activeGroupFilter={activeTelegramGroupFilter}
		{isTelegramBusy}
		hasSelectedTelegramChat={Boolean(selectedTelegramChat)}
		isInspectorOpen={isTelegramInspectorOpen}
		onSyncChats={() => void syncTelegramChats()}
		onSyncHistory={() => void syncSelectedTelegramHistory()}
		onStartRuntime={() => void startTelegramRuntime()}
		onSelectGroupFilter={selectTelegramGroupFilter}
		onToggleInspector={toggleTelegramInspector}
	/>

	<TelegramStatusMessages actionMessage={telegramActionMessage} error={telegramError} />

	<div class="three-pane communications-grid telegram-grid" class:inspector-open={isTelegramInspectorOpen}>
		<TelegramChatList
			telegramChats={filteredTelegramChats}
			telegramMessages={telegramMessages}
			selectedTelegramChatId={selectedTelegramChat?.provider_chat_id ?? ''}
			{isTelegramLoading}
			{isLayoutEditing}
			{isWidgetVisible}
			onSelectChat={selectTelegramChat}
			{formatDateTime}
		/>
		<TelegramMessageThread
			selectedTelegramChat={selectedTelegramChat}
			selectedTelegramMessages={selectedTelegramMessages}
			{aiAnalysisResult}
			selectedCommunication={selectedCommunication as { message_id?: string } | null}
			{isTelegramLoading}
			isTelegramActionSubmitting={isTelegramBusy}
			{isLayoutEditing}
			{isWidgetVisible}
			{activeThreadTab}
			onActiveThreadTabChange={(tab) => (activeThreadTab = tab)}
			onRailTabChange={(tab) => openTelegramInspector(tab)}
			telegramMessageTime={telegramMessageTime}
			{loadTelegramWorkspace}
			{syncSelectedTelegramHistory}
			{syncOlderTelegramHistory}
			{sendTelegramManualMessage}
			{downloadTelegramMedia}
			{telegramManualSendForm}
			{selectedTelegramRuntimeStatus}
		/>
		{#if isTelegramInspectorOpen}
			<TelegramRail
				{selectedTelegramChat}
				{activeRailTab}
				{isLayoutEditing}
				{isWidgetVisible}
				onActiveRailTabChange={(tab) => (activeRailTab = tab)}
				onClose={closeTelegramInspector}
			/>
		{/if}
	</div>

</section>

// frontend/src/domains/telegram/views/TelegramPage.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useI18n } from '../../../platform/i18n'
import { useNavigationStore } from '../../../shared/stores/navigation'

// Components
import TelegramActionRail from '../components/TelegramActionRail.vue'
import TelegramChatList from '../components/TelegramChatList.vue'
import TelegramCommandHeader from '../components/TelegramCommandHeader.vue'
import TelegramMessageThread from '../components/TelegramMessageThread.vue'
import TelegramRail from '../components/TelegramRail.vue'
import TelegramStatusMessages from '../components/TelegramStatusMessages.vue'

// Store
import { useTelegramStore, telegramChatGroupFilters, telegramMessageTime } from '../stores/telegram'

// TanStack Query
import { useTelegramCapabilitiesQuery } from '../queries/useTelegramQuery'

// API
import * as telegramApi from '../api/telegram'

const { t } = useI18n()
const navigationStore = useNavigationStore()
const store = useTelegramStore()

// Capabilities query
const { data: capabilities } = useTelegramCapabilitiesQuery()

// Computed
const runtimeLabel = computed(() => {
  if (!store.selectedTelegramRuntimeStatus) {
    return capabilities.value?.runtime_mode ?? t('Runtime Status')
  }
  return store.selectedTelegramRuntimeStatus.status
})

const filterTabs = computed(() => [
  { id: 'all' as const, label: 'All Chats' },
  { id: 'unread' as const, label: 'Unread' },
  { id: 'mentions' as const, label: 'Mentions' },
  { id: 'pinned' as const, label: 'Pinned' },
  { id: 'projects' as const, label: 'Projects' },
  { id: 'bots' as const, label: 'Bots' },
  { id: 'archived' as const, label: 'Archived' }
])

// Load data
onMounted(() => {
  void loadTelegramWorkspace()
})

async function loadTelegramWorkspace() {
  store.setTelegramLoading(true)
  try {
    const result = await telegramApi.loadTelegramWorkspace(
      store.selectedTelegramChatId,
      ''
    )
    store.setTelegramData(result)
    // Reset group filter if current group no longer exists
    const groups = telegramChatGroupFilters(store.telegramChats)
    if (!groups.some((g) => g.id === store.activeTelegramGroupFilter)) {
      store.activeTelegramGroupFilter = 'local:all'
    }
    const nextChat = store.telegramChats.find(
      (chat) => chat.provider_chat_id === store.selectedTelegramChatId
    ) ?? null
    void autoSyncTelegramHistory(nextChat)
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramLoading(false)
  }
}

function selectTelegramChat(chat: any) {
  store.selectTelegramChat(chat)
  void loadTelegramWorkspace()
}

const telegramAutoHistorySyncKeys = new Set<string>()

async function autoSyncTelegramHistory(chat: any) {
  if (!chat || store.isTelegramBusy) return
  const syncKey = `${chat.account_id}:${chat.provider_chat_id}`
  if (telegramAutoHistorySyncKeys.has(syncKey)) return
  if (chat.chat_kind !== 'private' && hasProjectedMessagesForChat(chat)) return

  telegramAutoHistorySyncKeys.add(syncKey)
  store.setTelegramHistorySyncing(true)
  store.setTelegramError('')
  try {
    const result = await telegramApi.syncTelegramSelectedHistory({
      account_id: chat.account_id,
      provider_chat_id: chat.provider_chat_id,
      chat_kind: chat.chat_kind
    })
    if (result.error) {
      telegramAutoHistorySyncKeys.delete(syncKey)
      store.setTelegramError(result.error)
    } else {
      store.setTelegramActionMessage(result.message)
      await loadTelegramWorkspace()
    }
  } finally {
    store.setTelegramHistorySyncing(false)
  }
}

function hasProjectedMessagesForChat(chat: any): boolean {
  return store.telegramMessages.some(
    (message) =>
      message.account_id === chat.account_id &&
      message.provider_chat_id === chat.provider_chat_id
  )
}

async function startTelegramRuntime() {
  if (store.isTelegramBusy || !store.selectedTelegramChat) return
  store.setTelegramActionSubmitting(true)
  store.setTelegramActionMessage('')
  store.setTelegramError('')
  try {
    const result = await telegramApi.startTelegramRuntimeFromUi(
      store.selectedTelegramChat.account_id
    )
    if (result.error) {
      store.setTelegramError(result.error)
    } else if (result.status) {
      store.updateRuntimeStatus(result.status.account_id, result.status)
      store.setTelegramActionMessage(result.message)
    }
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramActionSubmitting(false)
  }
}

async function syncTelegramChats() {
  if (store.isTelegramBusy || !store.selectedTelegramChat) return
  store.setTelegramActionSubmitting(true)
  store.setTelegramActionMessage('')
  store.setTelegramError('')
  try {
    const result = await telegramApi.syncTelegramChatsFromUi(
      store.selectedTelegramChat.account_id
    )
    if (result.error) {
      store.setTelegramError(result.error)
    } else {
      store.setTelegramActionMessage(result.message)
      await loadTelegramWorkspace()
    }
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramActionSubmitting(false)
  }
}

async function syncSelectedTelegramHistory() {
  if (store.isTelegramBusy || !store.selectedTelegramChat) return
  store.setTelegramActionSubmitting(true)
  store.setTelegramActionMessage('')
  store.setTelegramError('')
  try {
    const result = await telegramApi.syncTelegramSelectedHistory({
      account_id: store.selectedTelegramChat.account_id,
      provider_chat_id: store.selectedTelegramChat.provider_chat_id,
      chat_kind: store.selectedTelegramChat.chat_kind
    })
    if (result.error) {
      store.setTelegramError(result.error)
    } else {
      store.selectedTelegramChatId = result.providerChatId
      store.setTelegramActionMessage(result.message)
      await loadTelegramWorkspace()
    }
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramActionSubmitting(false)
  }
}

async function syncOlderTelegramHistory() {
  if (store.isTelegramBusy || !store.selectedTelegramChat) return
  const fromMessageId = telegramApi.telegramOldestTdlibMessageId(store.selectedTelegramMessages)
  if (fromMessageId === null) {
    await autoSyncTelegramHistory(store.selectedTelegramChat)
    return
  }
  store.setTelegramHistorySyncing(true)
  store.setTelegramError('')
  try {
    const result = await telegramApi.syncTelegramOlderHistory({
      account_id: store.selectedTelegramChat.account_id,
      provider_chat_id: store.selectedTelegramChat.provider_chat_id,
      from_message_id: fromMessageId
    })
    if (result.error) {
      store.setTelegramError(result.error)
    } else {
      store.setTelegramActionMessage(result.hasMore
        ? result.message
        : `${result.message}; ${t('no older Telegram messages')}`
      )
      await loadTelegramWorkspace()
    }
  } finally {
    store.setTelegramHistorySyncing(false)
  }
}

async function sendTelegramManualMessage() {
  if (store.isTelegramBusy || !store.selectedTelegramChat) return
  store.setTelegramActionSubmitting(true)
  store.setTelegramActionMessage('')
  store.setTelegramError('')
  try {
    const result = await telegramApi.sendTelegramManualMessage({
      account_id: store.selectedTelegramChat.account_id,
      provider_chat_id: store.selectedTelegramChat.provider_chat_id,
      text: store.telegramManualSendForm.text
    })
    if (result.error) {
      store.setTelegramError(result.error)
    } else {
      store.selectedTelegramChatId = result.providerChatId
      store.setTelegramActionMessage(result.message)
      store.telegramManualSendForm = { text: result.nextText }
      await loadTelegramWorkspace()
    }
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramActionSubmitting(false)
  }
}

async function downloadTelegramMedia(attachment: any, message?: any) {
  if (store.isTelegramBusy) return
  if (!store.selectedTelegramChat) {
    store.setTelegramError(t('Select a Telegram chat before downloading media.'))
    return
  }
  if (attachment.tdlibFileId === null) {
    store.setTelegramError(t('Telegram attachment does not include TDLib file metadata.'))
    return
  }
  const sourceMessage =
    message ??
    store.selectedTelegramMessages.find(
      (item: any) => item.message_id === attachment.messageId
    ) ??
    null
  if (!sourceMessage) {
    store.setTelegramError(t('Telegram source message is not available for this attachment.'))
    return
  }
  store.setTelegramActionSubmitting(true)
  store.setTelegramActionMessage('')
  store.setTelegramError('')
  try {
    const result = await telegramApi.downloadTelegramMediaFromUi({
      account_id: sourceMessage.account_id,
      provider_chat_id: sourceMessage.provider_chat_id || store.selectedTelegramChat.provider_chat_id,
      provider_message_id: sourceMessage.provider_message_id,
      tdlib_file_id: attachment.tdlibFileId,
      provider_attachment_id: attachment.providerAttachmentId,
      filename: attachment.fileName,
      content_type: attachment.mimeType ?? undefined,
      priority: 16
    })
    if (result.error) {
      store.setTelegramError(result.error)
    } else {
      store.setTelegramActionMessage(result.message)
      await loadTelegramWorkspace()
    }
  } catch (err) {
    store.setTelegramError(err instanceof Error ? err.message : String(err))
  } finally {
    store.setTelegramActionSubmitting(false)
  }
}

function openTelegramNewMessage() {
  store.closeTelegramMenus()
  store.activeThreadTab = 'messages'
  if (!store.selectedTelegramChat) {
    store.setTelegramActionMessage(t('Select a synced Telegram chat before composing.'))
    return
  }
  store.telegramManualSendForm = { text: '' }
  store.setTelegramActionMessage(`${t('Manual send target')}: ${store.selectedTelegramChat.title}`)
}

async function runTelegramQuickAction(action: 'create_note' | 'create_task' | 'create_contact' | 'create_document') {
  store.closeTelegramMenus()
  // Quick actions would use navigation store or a workflow action
}

function openTelegramAccountSetup() {
  // Would open account drawer
}

// Format helper
function formatDateTime(date: string | null): string {
  if (!date) return ''
  try {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return ''
  }
}
</script>

<template>
  <section class="telegram-page communications-page">
    <TelegramCommandHeader
      :runtimeLabel="runtimeLabel"
      :searchQuery="store.telegramSearchQuery"
      :filterTabs="filterTabs"
      :filterCounts="store.chatFilterCounts"
      :activeFilter="store.activeTelegramFilter"
      :isFiltersMenuOpen="store.isTelegramFiltersMenuOpen"
      :isNewMenuOpen="store.isTelegramNewMenuOpen"
      :isTelegramBusy="store.isTelegramBusy"
      :selectedTelegramChat="store.selectedTelegramChat"
      @update:searchQuery="store.telegramSearchQuery = $event"
      @toggleFiltersMenu="store.toggleTelegramFiltersMenu()"
      @toggleNewMenu="store.toggleTelegramNewMenu()"
      @selectFilter="store.selectTelegramFilter($event)"
      @syncChats="store.closeTelegramMenus(); void syncTelegramChats()"
      @addAccount="openTelegramAccountSetup"
      @newMessage="openTelegramNewMessage"
      @quickAction="(action) => void runTelegramQuickAction(action)"
    />

    <TelegramActionRail
      :groupFilters="store.chatGroupFilters"
      :activeGroupFilter="store.activeTelegramGroupFilter"
      :isTelegramBusy="store.isTelegramBusy"
      :hasSelectedTelegramChat="Boolean(store.selectedTelegramChat)"
      :isInspectorOpen="store.isTelegramInspectorOpen"
      @syncChats="void syncTelegramChats()"
      @syncHistory="void syncSelectedTelegramHistory()"
      @startRuntime="void startTelegramRuntime()"
      @selectGroupFilter="store.selectTelegramGroupFilter($event)"
      @toggleInspector="store.toggleTelegramInspector()"
    />

    <TelegramStatusMessages
      :actionMessage="store.telegramActionMessage"
      :error="store.telegramError"
    />

    <div
      class="three-pane communications-grid telegram-grid"
      :class="{ 'inspector-open': store.isTelegramInspectorOpen }"
    >
      <TelegramChatList
        :telegramChats="store.filteredTelegramChats"
        :telegramMessages="store.telegramMessages"
        :selectedTelegramChatId="store.selectedTelegramChat?.provider_chat_id ?? ''"
        :isTelegramLoading="store.isTelegramLoading"
        :formatDateTime="formatDateTime"
        @selectChat="selectTelegramChat"
      />

      <TelegramMessageThread
        :selectedTelegramChat="store.selectedTelegramChat"
        :selectedTelegramMessages="store.selectedTelegramMessages"
        :aiAnalysisResult="null"
        :selectedCommunication="null"
        :isTelegramLoading="store.isTelegramLoading"
        :isTelegramActionSubmitting="store.isTelegramBusy"
        :activeThreadTab="store.activeThreadTab"
        :telegramMessageTime="telegramMessageTime"
        :telegramManualSendForm="store.telegramManualSendForm"
        :selectedTelegramRuntimeStatus="store.selectedTelegramRuntimeStatus"
        @update:activeThreadTab="store.activeThreadTab = $event"
        @railTabChange="(tab) => store.openTelegramInspector(tab)"
        @loadWorkspace="void loadTelegramWorkspace()"
        @syncHistory="void syncSelectedTelegramHistory()"
        @syncOlderHistory="void syncOlderTelegramHistory()"
        @sendMessage="void sendTelegramManualMessage()"
        @downloadMedia="(attachment, message) => void downloadTelegramMedia(attachment, message)"
      />

      <TelegramRail
        v-if="store.isTelegramInspectorOpen"
        :selectedTelegramChat="store.selectedTelegramChat"
        :activeRailTab="store.activeRailTab"
        @update:activeRailTab="store.activeRailTab = $event"
        @close="store.closeTelegramInspector()"
      />
    </div>
  </section>
</template>

<style scoped>
.telegram-page {
  display: flex;
  flex-direction: column;
  height: 100%;
}
.communications-grid {
  display: flex;
  flex: 1;
  min-height: 0;
}
.three-pane {
  display: flex;
  flex: 1;
  overflow: hidden;
}
</style>
