// frontend/src/domains/personas/views/PersonsPage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../../../platform/i18n'
import { usePersonsQuery, useIdentityCandidatesQuery, useIdentityTracesQuery, useRelationshipsQuery } from '../queries/usePersonasQuery'
import { usePersonasStore } from '../stores/personas'
import PersonsList from '../components/PersonsList.vue'
import PersonsDetail from '../components/PersonsDetail.vue'
import PersonsIdentityReview from '../components/PersonsIdentityReview.vue'
import PersonsIdentityTraceReview from '../components/PersonsIdentityTraceReview.vue'
import PersonsRelationshipReview from '../components/PersonsRelationshipReview.vue'
import type { PersonItem, PersonIdentityCandidate } from '../types/persona'

const { t } = useI18n()
const store = usePersonasStore()

const { data: personsData } = usePersonsQuery()
const { data: identityCandidatesData } = useIdentityCandidatesQuery()
const { data: identityTracesData } = useIdentityTracesQuery()
const { data: relationshipsData } = useRelationshipsQuery()

const personList = computed<PersonItem[]>(() => {
  return (personsData.value ?? []).map((p) => ({
    person_id: p.person_id,
    name: p.display_name,
    role: p.preferred_channel || t('Contact'),
    company: p.email_address,
    status: p.last_interaction_at ? t('Online') : undefined,
    channel: p.preferred_channel ?? undefined
  }))
})

const selectedPerson = computed(() =>
  personList.value[store.selectedPersonIndex] ?? personList.value[0] ?? null
)

const suggestedIdentityCandidates = computed(() =>
  (identityCandidatesData.value ?? []).filter(
    (item: PersonIdentityCandidate) => item.review_state === 'suggested'
  )
)

const confirmedMergeIdentityCandidates = computed(() =>
  (identityCandidatesData.value ?? []).filter(
    (item: PersonIdentityCandidate) =>
      item.candidate_kind === 'merge_persons' &&
      item.review_state === 'user_confirmed'
  )
)

function identityConfidence(item: PersonIdentityCandidate): string {
  return `${Math.round(item.confidence * 100)}%`
}

async function setIdentityCandidateReview(candidate: PersonIdentityCandidate, state: string) {
  await store.reviewCandidate(candidate, state as any)
}

async function splitConfirmedIdentityMerge(candidate: PersonIdentityCandidate) {
  // Simplified: just mark back to suggested to re-evaluate
  await store.reviewCandidate(candidate, 'suggested' as any)
}

function splitCandidateForConfirmedMerge(candidate: PersonIdentityCandidate): PersonIdentityCandidate | null {
  return null
}

async function loadRelationships() {
  // Relationships loaded via TanStack Query
}

async function loadTraces() {
  // Traces loaded via TanStack Query
}
</script>

<template>
  <section class="persons-page">
    <div class="persons-layout">
      <PersonsList
        :personList="personList"
        :selectedPersonIndex="store.selectedPersonIndex"
        @selectPerson="store.selectPerson"
      />
      <PersonsDetail
        :selectedPerson="selectedPerson"
        :personDossier="store.personDossier"
        :isPersonDossierLoading="store.isPersonDossierLoading"
        :personDossierError="store.personDossierError"
        :whatsNew="[]"
        :projects="[]"
      />
      <aside class="stacked-rail">
        <div class="widget-frame" data-widget-id="persons-ai-summary">
          <section class="panel info-card">
            <h2>{{ t('AI Summary') }}</h2>
            <p>{{ t('John is a key strategic partner and decision maker. You have a strong professional relationship with frequent communication across multiple projects.') }}</p>
          </section>
        </div>
        <PersonsIdentityReview
          :suggestedIdentityCandidates="suggestedIdentityCandidates"
          :confirmedMergeIdentityCandidates="confirmedMergeIdentityCandidates"
          :isIdentityCandidatesLoading="false"
          :identityCandidatesError="store.identityCandidatesError"
          :identityConfidence="identityConfidence"
          :setIdentityCandidateReview="setIdentityCandidateReview"
          :splitConfirmedIdentityMerge="splitConfirmedIdentityMerge"
          :splitCandidateForConfirmedMerge="splitCandidateForConfirmedMerge"
        />
        <PersonsIdentityTraceReview
          :identityTraces="identityTracesData ?? []"
          :persons="personList"
          :selectedPersonaId="selectedPerson?.person_id ?? null"
          :isLoading="false"
          :error="store.identityTracesError"
          :assigningIdentityTraceId="store.assigningIdentityTraceId"
          :onReload="loadTraces"
          :onAssign="store.assignTraceToPersona"
        />
        <PersonsRelationshipReview
          :relationships="relationshipsData ?? []"
          :selectedPersonaId="selectedPerson?.person_id ?? null"
          :isLoading="false"
          :error="store.relationshipsError"
          :reviewingRelationshipId="store.reviewingRelationshipId"
          :onReload="loadRelationships"
          :onReview="store.reviewRelation"
        />
        <div class="widget-frame" data-widget-id="persons-related-documents">
          <section class="panel info-card">
            <h2>{{ t('Related Documents') }}</h2>
            <p>{{ t('Documents will appear here when processing is complete.') }}</p>
          </section>
        </div>
        <div class="widget-frame" data-widget-id="persons-recent-notes">
          <section class="panel info-card">
            <h2>{{ t('Recent Notes') }}</h2>
            <p>{{ t('Discussed expansion to EU market') }}</p>
            <p>{{ t('Prefers email for official communication') }}</p>
            <p>{{ t('Interested in AI/ML integration') }}</p>
          </section>
        </div>
      </aside>
    </div>
  </section>
</template>

<style scoped>
.persons-page {
  display: grid;
  grid-template-columns: repeat(var(--hh-layout-columns), minmax(0, 1fr));
  grid-auto-flow: row;
  grid-auto-rows: min-content;
  align-content: start;
  gap: var(--hh-layout-gap);
  height: 100%;
  min-height: 0;
  overflow: hidden;
  padding-right: 0;
}
.persons-page > * {
  grid-column: 1 / -1;
  min-width: 0;
}
.persons-layout {
  --hh-zone-rows: 12;
  display: grid;
  grid-template-columns: repeat(var(--hh-layout-columns), minmax(0, 1fr));
  grid-auto-flow: dense;
  grid-auto-rows: min-content;
  align-content: start;
  align-items: stretch;
  gap: var(--hh-layout-gap);
  width: 100%;
  min-width: 0;
  min-height: 0;
  max-height: 100%;
  overflow: hidden;
}
</style>

// frontend/src/lib/pages/persons/PersonsPage.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import * as personsService from '$lib/services/persons';
	import * as relationshipsService from '$lib/services/relationships';
	import type { PersonDossier, PersonIdentity, PersonIdentityCandidate, Relationship, RelationshipReviewState } from '$lib/api';
	import PersonsList from './widgets/PersonsList.svelte';
	import PersonsDetail from './widgets/PersonsDetail.svelte';
	import PersonsIdentityReview from './widgets/PersonsIdentityReview.svelte';
	import PersonsIdentityTraceReview from './widgets/PersonsIdentityTraceReview.svelte';
	import PersonsRelationshipReview from './widgets/PersonsRelationshipReview.svelte';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	type FeedItem = {
		icon: string;
		title: string;
		meta: string;
		time: string;
		tag?: string;
		tone?: string;
	};

	type ProjectItem = {
		name: string;
		kind: string;
		progress: number;
		icon: string;
		tone: string;
	};

	type DocItem = {
		icon: string;
		name: string;
		size: string;
		date: string;
	};

	type PersonItem = {
		person_id: string;
		name: string;
		role: string;
		company: string;
		channel?: string;
		status?: string;
	};

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();

	let persons = $state<PersonItem[]>([]);
	let personList = $state<PersonItem[]>([]);
	let selectedPersonIndex = $state(0);
	let personDossier = $state<PersonDossier | null>(null);
	let identityCandidates = $state<PersonIdentityCandidate[]>([]);
	let identityTraces = $state<PersonIdentity[]>([]);
	let relationships = $state<Relationship[]>([]);
	let isIdentityCandidatesLoading = $state(false);
	let identityCandidatesError = $state('');
	let isIdentityTracesLoading = $state(false);
	let identityTracesError = $state('');
	let assigningIdentityTraceId = $state<string | null>(null);
	let isPersonDossierLoading = $state(false);
	let personDossierError = $state('');
	let loadedDossierPersonId = $state<string | null>(null);
	let isRelationshipsLoading = $state(false);
	let relationshipsError = $state('');
	let reviewingRelationshipId = $state<string | null>(null);

	let selectedPerson = $derived(personList[selectedPersonIndex] ?? personList[0]);

	let suggestedIdentityCandidates = $derived(
		identityCandidates.filter((item) => item.review_state === 'suggested')
	);
	let confirmedMergeIdentityCandidates = $derived(
		identityCandidates.filter(
			(item) =>
				item.candidate_kind === 'merge_persons' &&
				item.review_state === 'user_confirmed' &&
				!confirmedSplitCandidateForMerge(item)
		)
	);

	function identityConfidence(item: PersonIdentityCandidate) {
		return `${Math.round(item.confidence * 100)}%`;
	}

	function confirmedSplitCandidateForMerge(candidate: PersonIdentityCandidate) {
		return splitCandidateForMerge(candidate, 'user_confirmed');
	}

	function splitCandidateForConfirmedMerge(candidate: PersonIdentityCandidate) {
		return splitCandidateForMerge(candidate, 'suggested');
	}

	function splitCandidateForMerge(
		candidate: PersonIdentityCandidate,
		reviewState: string
	): PersonIdentityCandidate | null {
		if (!candidate.right_person_id) return null;
		const pairKey = personIdentityPairKey(candidate.left_person_id, candidate.right_person_id);
		return (
			identityCandidates.find(
				(item) =>
					item.candidate_kind === 'split_person' &&
					item.review_state === reviewState &&
					item.right_person_id !== null &&
					personIdentityPairKey(item.left_person_id, item.right_person_id) === pairKey
			) ?? null
		);
	}

	function personIdentityPairKey(leftPersonId: string, rightPersonId: string) {
		return leftPersonId <= rightPersonId
			? `${leftPersonId}:${rightPersonId}`
			: `${rightPersonId}:${leftPersonId}`;
	}

	async function setIdentityCandidateReview(
		candidate: PersonIdentityCandidate,
		state: string
	) {
		const result = await personsService.setIdentityCandidateReview(
			candidate,
			state as 'suggested' | 'user_confirmed' | 'user_rejected'
		);
		if (result.error) {
			identityCandidatesError = result.error;
		} else {
			await loadIdentityCandidates();
		}
	}

	async function splitConfirmedIdentityMerge(candidate: PersonIdentityCandidate) {
		const splitCandidate = splitCandidateForConfirmedMerge(candidate);
		const result = await personsService.splitConfirmedIdentityMerge(candidate, splitCandidate);
		if (result.error) {
			identityCandidatesError = result.error;
		} else {
			await loadIdentityCandidates();
		}
	}

	async function loadPersons() {
		const result = await personsService.loadPersons();
		persons = result.persons.map((p) => ({
			person_id: p.person_id,
			name: p.display_name,
			role: p.preferred_channel || _('Contact'),
			company: p.email_address,
			status: p.last_interaction_at ? _('Online') : undefined,
			channel: p.preferred_channel ?? undefined
		}));
		personList = [...persons];
	}

	async function loadRelationshipReviewItems() {
		isRelationshipsLoading = true;
		const result = await relationshipsService.loadGlobalRelationshipReviewState();
		relationships = result.relationships;
		relationshipsError = result.error;
		isRelationshipsLoading = false;
	}

	async function setRelationshipReview(
		relationship: Relationship,
		reviewState: Exclude<RelationshipReviewState, 'suggested' | 'system_accepted'>
	) {
		reviewingRelationshipId = relationship.relationship_id;
		const result = await relationshipsService.reviewRelationshipItem(relationship, reviewState);
		if (result.error) {
			relationshipsError = result.error;
		} else {
			await loadRelationshipReviewItems();
		}
		reviewingRelationshipId = null;
	}

	async function loadIdentityCandidates() {
		isIdentityCandidatesLoading = true;
		const result = await personsService.loadIdentityCandidates();
		identityCandidates = result.candidates;
		identityCandidatesError = result.error;
		isIdentityCandidatesLoading = false;
	}

	async function loadSelectedPersonDossier(personId: string) {
		loadedDossierPersonId = personId;
		isPersonDossierLoading = true;
		const result = await personsService.loadPersonDossier(personId);
		if (loadedDossierPersonId === personId) {
			personDossier = result.dossier;
			personDossierError = result.error;
			isPersonDossierLoading = false;
		}
	}

	async function loadIdentityTraces() {
		isIdentityTracesLoading = true;
		const result = await personsService.loadIdentityTraces();
		identityTraces = result.identityTraces;
		identityTracesError = result.error;
		isIdentityTracesLoading = false;
	}

	async function assignIdentityTraceToPersona(trace: PersonIdentity, personId: string) {
		assigningIdentityTraceId = trace.id;
		const result = await personsService.assignIdentityTraceToPersona(trace, personId);
		if (result.error) {
			identityTracesError = result.error;
		} else {
			await loadIdentityTraces();
		}
		assigningIdentityTraceId = null;
	}

	$effect(() => {
		loadPersons();
		loadIdentityCandidates();
		loadIdentityTraces();
	});

	$effect(() => {
		const personId = selectedPerson?.person_id ?? null;
		if (!personId) {
			loadedDossierPersonId = null;
			personDossier = null;
			personDossierError = '';
			return;
		}
		if (personId !== loadedDossierPersonId) {
			void loadSelectedPersonDossier(personId);
		}
	});

	$effect(() => {
		loadRelationshipReviewItems();
	});
</script>

<section class="persons-page">
	<div class="persons-layout">
		<PersonsList
			{personList}
			{selectedPersonIndex}
			{isLayoutEditing}
			{isWidgetVisible}
			onSelectPerson={(index) => { selectedPersonIndex = index; }}
		/>
		<PersonsDetail
			{selectedPerson}
			{personDossier}
			{isPersonDossierLoading}
			{personDossierError}
			whatsNew={[]}
			projects={[]}
			{isLayoutEditing}
			{isWidgetVisible}
		/>
		<aside class="stacked-rail">
			<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="persons-ai-summary" data-widget-hidden={!isWidgetVisible('persons-ai-summary')}>
				<WidgetEditChrome widgetId="persons-ai-summary" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
				<section class="panel info-card"><h2>{_('AI Summary')}</h2><p>{_('John is a key strategic partner and decision maker. You have a strong professional relationship with frequent communication across multiple projects.')}</p></section>
			</div>
			<PersonsIdentityReview
				{suggestedIdentityCandidates}
				{confirmedMergeIdentityCandidates}
				{isIdentityCandidatesLoading}
				{identityCandidatesError}
				{isLayoutEditing}
				{isWidgetVisible}
				{identityConfidence}
				{setIdentityCandidateReview}
				{splitConfirmedIdentityMerge}
				{splitCandidateForConfirmedMerge}
			/>
			<PersonsIdentityTraceReview
				{identityTraces}
				persons={personList}
				selectedPersonaId={selectedPerson?.person_id ?? null}
				isLoading={isIdentityTracesLoading}
				error={identityTracesError}
				{assigningIdentityTraceId}
				{isLayoutEditing}
				{isWidgetVisible}
				onReload={loadIdentityTraces}
				onAssign={assignIdentityTraceToPersona}
			/>
			<PersonsRelationshipReview
				{relationships}
				selectedPersonaId={selectedPerson?.person_id ?? null}
				isLoading={isRelationshipsLoading}
				error={relationshipsError}
				{reviewingRelationshipId}
				{isLayoutEditing}
				{isWidgetVisible}
				onReload={loadRelationshipReviewItems}
				onReview={setRelationshipReview}
			/>
			<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="persons-related-documents" data-widget-hidden={!isWidgetVisible('persons-related-documents')}>
				<WidgetEditChrome widgetId="persons-related-documents" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
				<section class="panel info-card"><h2>{_('Related Documents')}</h2><p>{_('Documents will appear here when processing is complete.')}</p></section>
			</div>
			<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="persons-recent-notes" data-widget-hidden={!isWidgetVisible('persons-recent-notes')}>
				<WidgetEditChrome widgetId="persons-recent-notes" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
				<section class="panel info-card"><h2>{_('Recent Notes')}</h2><p>{_('Discussed expansion to EU market')}</p><p>{_('Prefers email for official communication')}</p><p>{_('Interested in AI/ML integration')}</p></section>
			</div>
		</aside>
	</div>

</section>
