// frontend/src/domains/settings/components/SidebarSettings.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import { useSidebarStore, type SidebarItemId, type SidebarNavGroup, type ResolvedSidebarItem, type ResolvedSidebarRootEntry } from '../../../shared/stores/sidebar'
import { useSettingsStore } from '../stores/settings'
import { saveApplicationSetting } from '../api/settings'
import { FRONTEND_SIDEBAR_SETTING_KEY } from '../types/settings'
import { useQueryClient } from '@tanstack/vue-query'
import { settingsKeys } from '../queries/useSettingsQuery'

const { t } = useI18n()
const sidebar = useSidebarStore()
const store = useSettingsStore()
const queryClient = useQueryClient()

function sidebarGroupLabel(group: SidebarNavGroup, index: number): string {
  return group.label || (group.id === 'communications' ? 'Communications' : `Group ${index + 1}`)
}

function sidebarItemLabel(item: ResolvedSidebarItem): string {
  return item.label
}

function sidebarGroupHasSeparatorBefore(group: SidebarNavGroup, itemId: SidebarItemId): boolean {
  return group.itemIds.indexOf(itemId) > 0 && group.separatorBeforeItemIds.includes(itemId)
}

function sidebarRootIndexForGroup(groupId: string): number {
  return sidebar.effectiveSidebarSettings.rootItemIds.indexOf(`group:${sidebar.sidebarGroupIdFromLabel(groupId)}`)
}

function sidebarConfigItem(itemId: SidebarItemId): { id: SidebarItemId; label: string; icon: string } | null {
  return sidebar.sidebarConfigItem(itemId)
}

function sidebarGroupIdFromLabelFn(label: string): string {
  if (label.startsWith('group:')) {
    const groupId = label.slice('group:'.length)
    return sidebar.effectiveSidebarSettings.groups.find((g) => sidebar.sidebarGroupIdFromLabel(g.id) === groupId)?.id ?? ''
  }
  return ''
}

function sidebarMoveTargetOptions(includeRoot: boolean) {
  return [
    ...(includeRoot ? [{ value: 'root', label: t('Root level') }] : []),
    ...sidebar.effectiveSidebarSettings.groups.map((group, index) => ({
      value: group.id,
      label: sidebarGroupLabel(group, index)
    }))
  ]
}

async function handleSaveSidebar() {
  store.isSidebarSettingsSaving = true
  store.sidebarError = ''
  try {
    await saveApplicationSetting(FRONTEND_SIDEBAR_SETTING_KEY, sidebar.effectiveSidebarSettings as any)
    sidebar.setSidebarSettings(sidebar.effectiveSidebarSettings)
    queryClient.invalidateQueries({ queryKey: settingsKeys.application() })
    store.setActionMessage(t('Sidebar saved'))
  } catch (err) {
    store.sidebarError = err instanceof Error ? err.message : t('Failed to save sidebar')
  } finally {
    store.isSidebarSettingsSaving = false
  }
}

function handleMoveSidebarItemToGroup(itemId: SidebarItemId, targetGroupId: string) {
  sidebar.moveSidebarItemToGroup(itemId, targetGroupId)
}
</script>

<template>
  <div class="settings-layout sidebar-settings-layout">
    <section class="panel settings-list-panel settings-primary-pane sidebar-settings-panel">
      <header class="panel-title-row">
        <div>
          <h2>{{ t('Sidebar Navigation') }}</h2>
          <p>{{ t('Configure workspace groups, order and hidden domains.') }}</p>
        </div>
        <div class="sidebar-settings-actions">
          <button
            type="button"
            class="hermes-btn hermes-btn--outline"
            :disabled="!sidebar.sidebarDraft || store.isSidebarSettingsSaving"
            @click="sidebar.cancelSidebarSettingsEditing()"
          >
            {{ t('Cancel') }}
          </button>
          <button
            type="button"
            class="hermes-btn hermes-btn--outline"
            :disabled="store.isSidebarSettingsSaving"
            @click="sidebar.resetSidebarSettingsToDefault()"
          >
            {{ t('Default') }}
          </button>
          <button
            type="button"
            class="hermes-btn hermes-btn--primary"
            :disabled="!sidebar.sidebarDraft || store.isSidebarSettingsSaving"
            @click="handleSaveSidebar"
          >
            {{ store.isSidebarSettingsSaving ? t('Saving...') : t('Save') }}
          </button>
        </div>
      </header>

      <div v-if="store.sidebarError" class="inline-error">{{ store.sidebarError }}</div>

      <!-- Create group form -->
      <form
        class="sidebar-group-create"
        @submit.prevent="sidebar.addSidebarGroup()"
      >
        <label>
          <span>{{ t('New group') }}</span>
          <input
            v-model="store.newSidebarGroupLabel"
            :placeholder="t('Focus, Library, Planning')"
            autocomplete="off"
          />
        </label>
        <button type="submit" class="hermes-btn hermes-btn--secondary">
          {{ t('Create Group') }}
        </button>
      </form>

      <div class="sidebar-config-list">
        <!-- Root level section -->
        <section class="sidebar-config-group">
          <header>
            <label>
              <span>{{ t('Root level') }}</span>
              <input :value="t('Sidebar root')" disabled autocomplete="off" />
            </label>
          </header>
          <div class="sidebar-config-items">
            <template v-for="(rootId, rootIndex) in sidebar.effectiveSidebarSettings.rootItemIds" :key="rootId">
              <!-- If it's a group rootId -->
              <template v-if="sidebarGroupIdFromLabelFn(rootId)">
                <div
                  v-for="group in sidebar.effectiveSidebarSettings.groups.filter(g => sidebarGroupIdFromLabelFn(rootId) === g.id)"
                  :key="group.id"
                  class="sidebar-config-item group-node"
                >
                  <div class="sidebar-config-item-main">
                    <span class="round-icon green">
                      {{ group.icon }}
                    </span>
                    <div>
                      <strong>{{ sidebarGroupLabel(group, rootIndex) }}</strong>
                      <small>{{ t('Expandable group') }} · {{ group.itemIds.length }} {{ t('items') }}</small>
                    </div>
                  </div>
                  <div class="sidebar-config-item-controls">
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :disabled="rootIndex === 0"
                      @click="sidebar.moveSidebarGroup(group.id, -1)"
                    >
                      ↑
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :disabled="rootIndex === sidebar.effectiveSidebarSettings.rootItemIds.length - 1"
                      @click="sidebar.moveSidebarGroup(group.id, 1)"
                    >
                      ↓
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon hermes-btn--destructive"
                      :disabled="group.id === 'communications'"
                      @click="sidebar.removeSidebarGroup(group.id)"
                    >
                      ✕
                    </button>
                  </div>
                </div>
              </template>

              <!-- If it's a root item (not a group) -->
              <template v-else>
                <div
                  v-for="item in [sidebarConfigItem(rootId as SidebarItemId)].filter(Boolean)"
                  :key="item!.id"
                  class="sidebar-config-item"
                  :class="{ hidden: sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) }"
                >
                  <div class="sidebar-config-item-main">
                    <span class="round-icon cyan">{{ item!.icon }}</span>
                    <div>
                      <strong>{{ item!.label }}</strong>
                      <small>{{ sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) ? t('Hidden from sidebar') : t('Root domain') }}</small>
                    </div>
                  </div>
                  <div class="sidebar-config-item-controls">
                    <select
                      class="hermes-select-control"
                      value="root"
                      @change="(e) => handleMoveSidebarItemToGroup(item!.id, (e.target as HTMLSelectElement).value)"
                    >
                      <option value="root" disabled>{{ t('Move to group') }}</option>
                      <option
                        v-for="opt in sidebarMoveTargetOptions(true)"
                        :key="opt.value"
                        :value="opt.value"
                      >
                        {{ opt.label }}
                      </option>
                    </select>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :disabled="rootIndex === 0"
                      @click="sidebar.moveSidebarRootItem(rootId, -1)"
                    >
                      ↑
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :disabled="rootIndex === sidebar.effectiveSidebarSettings.rootItemIds.length - 1"
                      @click="sidebar.moveSidebarRootItem(rootId, 1)"
                    >
                      ↓
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :class="{ active: !sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) }"
                      @click="sidebar.toggleSidebarItemHidden(item!.id)"
                    >
                      {{ sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) ? t('Show') : t('Hide') }}
                    </button>
                  </div>
                </div>
              </template>
            </template>
          </div>
        </section>

        <!-- Per-group sections -->
        <section
          v-for="(group, groupIndex) in sidebar.effectiveSidebarSettings.groups"
          :key="group.id"
          class="sidebar-config-group"
        >
          <header>
            <label>
              <span>{{ t('Group label') }}</span>
              <input
                :value="group.label"
                :placeholder="groupIndex === 0 ? t('Primary') : t('Group {n}').replace('{n}', String(groupIndex + 1))"
                autocomplete="off"
                @input="(e) => sidebar.updateSidebarGroupLabel(group.id, (e.target as HTMLInputElement).value)"
              />
            </label>
            <div class="sidebar-config-group-actions">
              <button
                type="button"
                class="hermes-btn hermes-btn--icon"
                :disabled="sidebarRootIndexForGroup(group.id) <= 0"
                @click="sidebar.moveSidebarGroup(group.id, -1)"
              >
                ↑
              </button>
              <button
                type="button"
                class="hermes-btn hermes-btn--icon"
                :disabled="sidebarRootIndexForGroup(group.id) === sidebar.effectiveSidebarSettings.rootItemIds.length - 1"
                @click="sidebar.moveSidebarGroup(group.id, 1)"
              >
                ↓
              </button>
              <button
                type="button"
                class="hermes-btn hermes-btn--icon hermes-btn--destructive"
                :disabled="group.id === 'communications'"
                @click="sidebar.removeSidebarGroup(group.id)"
              >
                ✕
              </button>
            </div>
          </header>
          <div class="sidebar-config-items">
            <div v-if="group.itemIds.length === 0" class="empty-panel">
              {{ t('No items in this group.') }}
            </div>
            <template v-else>
              <div
                v-for="(itemId, itemIndex) in group.itemIds"
                :key="itemId"
              >
                <div
                  v-for="item in [sidebarConfigItem(itemId)].filter(Boolean)"
                  :key="item!.id"
                  class="sidebar-config-item"
                  :class="{ hidden: sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) }"
                >
                  <div class="sidebar-config-item-main">
                    <span class="round-icon cyan">{{ item!.icon }}</span>
                    <div>
                      <strong>{{ item!.label }}</strong>
                      <small>{{ sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) ? t('Hidden from sidebar') : t('Visible domain') }}</small>
                    </div>
                  </div>
                  <div class="sidebar-config-item-controls">
                    <select
                      class="hermes-select-control"
                      :value="group.id"
                      @change="(e) => handleMoveSidebarItemToGroup(item!.id, (e.target as HTMLSelectElement).value)"
                    >
                      <option :value="group.id" disabled>{{ t('Move to group') }}</option>
                      <option
                        v-for="opt in sidebarMoveTargetOptions(false)"
                        :key="opt.value"
                        :value="opt.value"
                      >
                        {{ opt.label }}
                      </option>
                    </select>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      @click="sidebar.moveSidebarItem(item!.id, -1)"
                    >
                      ↑
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      @click="sidebar.moveSidebarItem(item!.id, 1)"
                    >
                      ↓
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :class="{ active: sidebarGroupHasSeparatorBefore(group, item!.id) }"
                      :disabled="itemIndex === 0"
                      @click="sidebar.toggleSidebarGroupSeparator(group.id, item!.id)"
                    >
                      {{ t('Divider') }}
                    </button>
                    <button
                      type="button"
                      class="hermes-btn hermes-btn--icon"
                      :class="{ active: !sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) }"
                      @click="sidebar.toggleSidebarItemHidden(item!.id)"
                    >
                      {{ sidebar.effectiveSidebarSettings.hiddenItemIds.includes(item!.id) ? t('Show') : t('Hide') }}
                    </button>
                  </div>
                </div>
              </div>
            </template>
          </div>
        </section>
      </div>
    </section>

    <aside class="settings-rail sidebar-settings-summary">
      <section class="panel info-card">
        <h2>{{ t('Preview') }}</h2>
        <ul class="sidebar-preview-list">
          <li v-for="(entry, entryIndex) in sidebar.sidebarRootEntries" :key="entryIndex">
            <template v-if="entry.kind === 'group'">
              <strong>{{ sidebarGroupLabel(entry.group, entryIndex) }}</strong>
              <span>{{ entry.group.items.map((i) => sidebarItemLabel(i)).join(', ') || t('Empty group') }}</span>
            </template>
            <template v-else>
              <strong>{{ sidebarItemLabel(entry.item) }}</strong>
              <span>{{ t('Root domain') }}</span>
            </template>
          </li>
        </ul>
      </section>
      <section class="panel info-card">
        <h2>{{ t('Hidden') }}</h2>
        <p v-if="sidebar.sidebarHiddenNavItems.length === 0">{{ t('No domains are hidden.') }}</p>
        <ul v-else class="detail-list">
          <li v-for="itemId in sidebar.sidebarHiddenNavItems" :key="itemId">
            <template v-for="item in [sidebarConfigItem(itemId)].filter(Boolean)" :key="item!.id">
              {{ item!.label }}
              <button type="button" class="hermes-btn hermes-btn--ghost" @click="sidebar.toggleSidebarItemHidden(item!.id)">
                {{ t('Show') }}
              </button>
            </template>
          </li>
        </ul>
      </section>
      <section class="panel info-card">
        <h2>{{ t('Rules') }}</h2>
        <ul class="detail-list">
          <li>{{ t('Default keeps the current sidebar order') }}<em>{{ t('Preset') }}</em></li>
          <li>{{ t('Communications sources stay nested') }}<em>{{ t('Context') }}</em></li>
          <li>{{ t('Hidden domains stay recoverable here') }}<em>{{ t('Safe') }}</em></li>
          <li>{{ t('Settings store no message content') }}<em>{{ t('Privacy') }}</em></li>
        </ul>
      </section>
    </aside>
  </div>
</template>

<style scoped>
.sidebar-settings-layout {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(260px, 310px);
  gap: var(--hh-layout-gap);
  height: 100%;
  min-height: 0;
  overflow: hidden;
}

.sidebar-settings-panel {
  display: flex;
  flex-direction: column;
  min-width: 0;
  min-height: 0;
}

.sidebar-settings-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.sidebar-group-create {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  border-top: 1px solid var(--hh-border);
}

.sidebar-group-create label {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  font-size: 12px;
  color: var(--hh-text-secondary);
}

.sidebar-group-create input {
  flex: 1;
  min-width: 0;
  height: 34px;
  padding: 0 10px;
  background: var(--hh-surface-deep);
  border: 1px solid var(--hh-border);
  border-radius: var(--hh-radius-sm);
  color: var(--hh-text-primary);
  font-size: 12px;
  outline: none;
}

.sidebar-group-create input:focus-visible {
  box-shadow: 0 0 0 2px var(--hh-focus-ring);
  border-color: var(--hh-accent);
}

.sidebar-config-list {
  flex: 1 1 auto;
  min-height: 0;
  overflow-x: hidden;
  overflow-y: auto;
  padding: 8px;
}

.sidebar-config-group {
  margin-bottom: 12px;
}

.sidebar-config-group > header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 8px;
  border-bottom: 1px solid var(--hh-border);
}

.sidebar-config-group > header label {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 11px;
  color: var(--hh-text-secondary);
}

.sidebar-config-group > header input {
  max-width: 180px;
  height: 28px;
  padding: 0 8px;
  background: var(--hh-surface-deep);
  border: 1px solid var(--hh-border);
  border-radius: var(--hh-radius-sm);
  color: var(--hh-text-primary);
  font-size: 12px;
  outline: none;
}

.sidebar-config-group > header input:focus-visible {
  box-shadow: 0 0 0 2px var(--hh-focus-ring);
  border-color: var(--hh-accent);
}

.sidebar-config-group-actions {
  display: flex;
  gap: 4px;
}

.sidebar-config-items {
  display: grid;
  gap: 4px;
  padding: 4px 0;
}

.sidebar-config-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 8px;
  border-radius: var(--hh-radius-sm);
  transition: background 100ms ease;
}

.sidebar-config-item:hover {
  background: var(--hh-hover-bg);
}

.sidebar-config-item.hidden {
  opacity: 0.5;
}

.sidebar-config-item.group-node {
  border-left: 2px solid var(--hh-accent);
}

.sidebar-config-item-main {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.sidebar-config-item-main strong {
  display: block;
  font-size: 12px;
  font-weight: 620;
  color: var(--hh-text-primary);
}

.sidebar-config-item-main small {
  font-size: 10px;
  color: var(--hh-text-muted);
}

.sidebar-config-item-controls {
  display: flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}

.round-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  font-size: 14px;
  flex-shrink: 0;
}

.round-icon.green {
  background: color-mix(in srgb, #22c55e 15%, transparent);
  color: #22c55e;
}

.round-icon.cyan {
  background: color-mix(in srgb, var(--hh-accent) 15%, transparent);
  color: var(--hh-accent);
}

/* Rail */
.settings-rail {
  display: grid;
  gap: 12px;
  align-content: start;
  min-width: 0;
  min-height: 0;
  max-height: 100%;
  overflow-x: hidden;
  overflow-y: auto;
}

.sidebar-preview-list {
  display: grid;
  gap: 6px;
  list-style: none;
  padding: 0;
  margin: 0;
}

.sidebar-preview-list li {
  display: grid;
  gap: 2px;
}

.sidebar-preview-list li strong {
  font-size: 12px;
  font-weight: 620;
  color: var(--hh-text-primary);
}

.sidebar-preview-list li span {
  font-size: 10px;
  color: var(--hh-text-muted);
}

.detail-list {
  display: grid;
  gap: 6px;
  list-style: none;
  padding: 0;
  margin: 0;
}

.detail-list li {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 11px;
  color: var(--hh-text-secondary);
}

.detail-list li em {
  font-size: 9px;
  font-weight: 720;
  color: var(--hh-accent);
  font-style: normal;
  text-transform: uppercase;
}

.inline-error {
  padding: 8px 12px;
  background: color-mix(in srgb, var(--hh-status-danger) 15%, transparent);
  border: 1px solid color-mix(in srgb, var(--hh-status-danger) 30%, transparent);
  border-radius: var(--hh-radius-sm);
  color: var(--hh-status-danger);
  font-size: 12px;
  margin: 8px;
}
</style>

// frontend/src/lib/pages/settings/widgets/SidebarSettings.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import type { SidebarSettings, SidebarNavGroup, SidebarItemId, SidebarRootItemId, ResolvedSidebarItem, ResolvedSidebarRootEntry, PrimaryNavId } from '$lib/layout';
	import { parseCommunicationSidebarItemId } from '$lib/layout';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		sidebarError: string;
		isSidebarSettingsSaving: boolean;
		newSidebarGroupLabel: string;
		sidebarRootEntries: ResolvedSidebarRootEntry<{ id: PrimaryNavId; label: string; icon: string; badge?: string; enabled: boolean }>[];
		sidebarHiddenNavItems: Array<{ id: SidebarItemId; label: string; icon: string }>;

		effectiveSidebarSettings: SidebarSettings;
		hasSidebarChanges: boolean;

		onCancelSidebarEditing: () => void;
		onResetSidebar: () => void;
		onSaveSidebar: () => Promise<void>;
		onAddSidebarGroup: () => void;
		onRemoveSidebarGroup: (groupId: string) => void;
		onMoveSidebarGroup: (groupId: string, direction: -1 | 1) => void;
		onMoveSidebarRootItem: (rootId: SidebarRootItemId, direction: -1 | 1) => void;
		onMoveSidebarItem: (itemId: SidebarItemId, direction: -1 | 1) => void;
		onMoveSidebarItemToGroup: (itemId: SidebarItemId, targetGroupId: string) => void;
		onToggleSidebarGroupSeparator: (groupId: string, itemId: SidebarItemId) => void;
		onToggleSidebarItemHidden: (itemId: SidebarItemId) => void;
		onUpdateSidebarGroupLabel: (groupId: string, label: string) => void;
		onUpdateNewSidebarGroupLabel: (label: string) => void;

		sidebarGroupLabelFn: (group: SidebarNavGroup, index: number) => string;
		sidebarItemLabelFn: (item: ResolvedSidebarItem<{ id: PrimaryNavId; label: string; icon: string; badge?: string; enabled: boolean }>) => string;
		sidebarGroupHasSeparatorBeforeFn: (group: SidebarNavGroup, itemId: SidebarItemId) => boolean;
		sidebarRootIndexForGroupFn: (groupId: string) => number;
		sidebarGroupIdFromLabelFn: (label: string) => string;
		sidebarConfigItemFn: (itemId: SidebarItemId) => { id: SidebarItemId; label: string; icon: string } | null;
		inputEventValueFn: (event: Event) => string;
	}

	let {
		sidebarError,
		isSidebarSettingsSaving,
		newSidebarGroupLabel,
		sidebarRootEntries,
		sidebarHiddenNavItems,
		effectiveSidebarSettings,
		hasSidebarChanges,
		onCancelSidebarEditing,
		onResetSidebar,
		onSaveSidebar,
		onAddSidebarGroup,
		onRemoveSidebarGroup,
		onMoveSidebarGroup,
		onMoveSidebarRootItem,
		onMoveSidebarItem,
		onMoveSidebarItemToGroup,
		onToggleSidebarGroupSeparator,
		onToggleSidebarItemHidden,
		onUpdateSidebarGroupLabel,
		onUpdateNewSidebarGroupLabel,
		sidebarGroupLabelFn,
		sidebarItemLabelFn,
		sidebarGroupHasSeparatorBeforeFn,
		sidebarRootIndexForGroupFn,
		sidebarGroupIdFromLabelFn,
		sidebarConfigItemFn,
		inputEventValueFn
	}: Props = $props();
</script>

<div class="settings-layout sidebar-settings-layout">
	<section class="panel settings-list-panel settings-primary-pane sidebar-settings-panel">
		<header class="panel-title-row">
			<div>
				<h2>{_('Sidebar Navigation')}</h2>
				<p>{_('Configure workspace groups, order and hidden domains. Communications sources stay inside Communications.')}</p>
			</div>
			<div class="sidebar-settings-actions">
				<button type="button" onclick={onCancelSidebarEditing} disabled={!hasSidebarChanges || isSidebarSettingsSaving}>
					<Icon icon="tabler:arrow-back-up" width="16" height="16" />{_('Cancel')}
				</button>
				<button type="button" onclick={onResetSidebar} disabled={isSidebarSettingsSaving}>
					<Icon icon="tabler:restore" width="16" height="16" />{_('Default')}
				</button>
				<button type="button" class="primary-button" onclick={() => void onSaveSidebar()} disabled={!hasSidebarChanges || isSidebarSettingsSaving}>
					<Icon icon="tabler:device-floppy" width="16" height="16" />{isSidebarSettingsSaving ? _('Saving') : _('Save')}
				</button>
			</div>
		</header>

		{#if sidebarError}
			<p class="inline-error">{sidebarError}</p>
		{/if}

		<form class="sidebar-group-create" onsubmit={(event) => { event.preventDefault(); onAddSidebarGroup(); }}>
			<label>
				<span>{_('New group')}</span>
				<input value={newSidebarGroupLabel} placeholder={_('Focus, Library, Planning')} autocomplete="off" oninput={(event) => onUpdateNewSidebarGroupLabel(inputEventValueFn(event))} />
			</label>
			<button type="submit">
				<Icon icon="tabler:plus" width="16" height="16" />{_('Create Group')}
			</button>
		</form>

		<div class="sidebar-config-list">
			<section class="sidebar-config-group">
				<header>
					<label>
						<span>{_('Root level')}</span>
						<input value={_('Sidebar root')} disabled autocomplete="off" />
					</label>
				</header>
				<div class="sidebar-config-items">
					{#each effectiveSidebarSettings.rootItemIds as rootId, rootIndex}
						{@const groupId = sidebarGroupIdFromLabelFn(rootId)}
						{#if groupId}
							{@const group = effectiveSidebarSettings.groups.find((item) => item.id === groupId)}
							{#if group}
								<div class="sidebar-config-item group-node">
									<div class="sidebar-config-item-main">
										<span class="round-icon green"><Icon icon={group.icon} width="18" height="18" /></span>
										<div>
											<strong>{_(sidebarGroupLabelFn(group, rootIndex))}</strong>
											<small>{_('Expandable group')} · {group.itemIds.length} {_('items')}</small>
										</div>
									</div>
									<div class="sidebar-config-item-controls">
										<button type="button" aria-label={_('Move {label} up').replace('{label}', _(sidebarGroupLabelFn(group, rootIndex)))} title={_('Move group up')} onclick={() => onMoveSidebarGroup(group.id, -1)} disabled={rootIndex === 0}>
											<Icon icon="tabler:arrow-up" width="16" height="16" />
										</button>
										<button type="button" aria-label={_('Move {label} down').replace('{label}', _(sidebarGroupLabelFn(group, rootIndex)))} title={_('Move group down')} onclick={() => onMoveSidebarGroup(group.id, 1)} disabled={rootIndex === effectiveSidebarSettings.rootItemIds.length - 1}>
											<Icon icon="tabler:arrow-down" width="16" height="16" />
										</button>
										<button type="button" aria-label={_('Remove {label} group').replace('{label}', _(sidebarGroupLabelFn(group, rootIndex)))} title={_('Remove group')} onclick={() => onRemoveSidebarGroup(group.id)} disabled={group.id === 'communications'}>
											<Icon icon="tabler:trash" width="16" height="16" />
										</button>
									</div>
								</div>
							{/if}
						{:else}
							{@const item = sidebarConfigItemFn(rootId as SidebarItemId)}
							{#if item}
								{@const isHidden = effectiveSidebarSettings.hiddenItemIds.includes(item.id)}
								<div class="sidebar-config-item" class:hidden={isHidden}>
									<div class="sidebar-config-item-main">
										<span class="round-icon cyan"><Icon icon={item.icon} width="18" height="18" /></span>
										<div>
											<strong>{item.label}</strong>
											<small>{isHidden ? _('Hidden from sidebar') : _('Root domain')}</small>
										</div>
									</div>
									<div class="sidebar-config-item-controls">
										<select aria-label={_('Move {label} to group').replace('{label}', item.label)} value="root" onchange={(event) => onMoveSidebarItemToGroup(item.id, inputEventValueFn(event))}>
											<option value="root">{_('Root level')}</option>
											{#each effectiveSidebarSettings.groups as targetGroup, targetIndex}
												<option value={targetGroup.id}>{_(sidebarGroupLabelFn(targetGroup, targetIndex))}</option>
											{/each}
										</select>
										<button type="button" aria-label={_('Move {label} up').replace('{label}', item.label)} title={_('Move item up')} onclick={() => onMoveSidebarRootItem(rootId, -1)} disabled={rootIndex === 0}>
											<Icon icon="tabler:arrow-up" width="16" height="16" />
										</button>
										<button type="button" aria-label={_('Move {label} down').replace('{label}', item.label)} title={_('Move item down')} onclick={() => onMoveSidebarRootItem(rootId, 1)} disabled={rootIndex === effectiveSidebarSettings.rootItemIds.length - 1}>
											<Icon icon="tabler:arrow-down" width="16" height="16" />
										</button>
										<button type="button" class:active={!isHidden} aria-pressed={!isHidden} onclick={() => onToggleSidebarItemHidden(item.id)}>
											<Icon icon={isHidden ? 'tabler:eye' : 'tabler:eye-off'} width="16" height="16" />{isHidden ? _('Show') : _('Hide')}
										</button>
									</div>
								</div>
							{/if}
						{/if}
					{/each}
				</div>
			</section>

			{#each effectiveSidebarSettings.groups as group, groupIndex}
				<section class="sidebar-config-group">
					<header>
						<label>
							<span>{_('Group label')}</span>
							<input value={group.label} placeholder={groupIndex === 0 ? _('Primary') : _('Group {n}').replace('{n}', String(groupIndex + 1))} autocomplete="off" oninput={(event) => onUpdateSidebarGroupLabel(group.id, inputEventValueFn(event))} />
						</label>
						<div class="sidebar-config-group-actions">
							<button type="button" aria-label={_('Move {label} up').replace('{label}', _(sidebarGroupLabelFn(group, groupIndex)))} title={_('Move group up')} onclick={() => onMoveSidebarGroup(group.id, -1)} disabled={sidebarRootIndexForGroupFn(group.id) <= 0}>
								<Icon icon="tabler:arrow-up" width="16" height="16" />
							</button>
							<button type="button" aria-label={_('Move {label} down').replace('{label}', _(sidebarGroupLabelFn(group, groupIndex)))} title={_('Move group down')} onclick={() => onMoveSidebarGroup(group.id, 1)} disabled={sidebarRootIndexForGroupFn(group.id) === effectiveSidebarSettings.rootItemIds.length - 1}>
								<Icon icon="tabler:arrow-down" width="16" height="16" />
							</button>
							<button type="button" aria-label={_('Remove {label} group').replace('{label}', _(sidebarGroupLabelFn(group, groupIndex)))} title={_('Remove group')} onclick={() => onRemoveSidebarGroup(group.id)} disabled={group.id === 'communications'}>
								<Icon icon="tabler:trash" width="16" height="16" />
							</button>
						</div>
					</header>
					<div class="sidebar-config-items">
						{#if group.itemIds.length === 0}
							<div class="empty-panel">{_('No items in this group.')}</div>
						{:else}
							{#each group.itemIds as itemId, itemIndex}
								{@const item = sidebarConfigItemFn(itemId)}
								{#if item}
									{@const isHidden = effectiveSidebarSettings.hiddenItemIds.includes(item.id)}
									{@const hasSeparator = sidebarGroupHasSeparatorBeforeFn(group, item.id)}
									<div class="sidebar-config-item" class:hidden={isHidden}>
										<div class="sidebar-config-item-main">
											<span class="round-icon cyan"><Icon icon={item.icon} width="18" height="18" /></span>
											<div>
												<strong>{item.label}</strong>
												<small>{isHidden ? _('Hidden from sidebar') : _('Visible domain')}</small>
											</div>
										</div>
										<div class="sidebar-config-item-controls">
											<select aria-label={_('Move {label} to group').replace('{label}', item.label)} value={group.id} onchange={(event) => onMoveSidebarItemToGroup(item.id, inputEventValueFn(event))}>
												{#if !parseCommunicationSidebarItemId(item.id)}
													<option value="root">{_('Root level')}</option>
												{/if}
												{#each effectiveSidebarSettings.groups as targetGroup, targetIndex}
													<option value={targetGroup.id}>{_(sidebarGroupLabelFn(targetGroup, targetIndex))}</option>
												{/each}
											</select>
											<button type="button" aria-label={_('Move {label} up').replace('{label}', item.label)} title={_('Move item up')} onclick={() => onMoveSidebarItem(item.id, -1)}>
												<Icon icon="tabler:arrow-up" width="16" height="16" />
											</button>
											<button type="button" aria-label={_('Move {label} down').replace('{label}', item.label)} title={_('Move item down')} onclick={() => onMoveSidebarItem(item.id, 1)}>
												<Icon icon="tabler:arrow-down" width="16" height="16" />
											</button>
											<button type="button" class="separator-toggle" class:active={hasSeparator} aria-pressed={hasSeparator} aria-label={hasSeparator ? _('Remove divider before {label}').replace('{label}', item.label) : _('Add divider before {label}').replace('{label}', item.label)} title={hasSeparator ? _('Remove divider before {label}').replace('{label}', item.label) : _('Add divider before {label}').replace('{label}', item.label)} onclick={() => onToggleSidebarGroupSeparator(group.id, item.id)} disabled={itemIndex === 0}>
												<Icon icon="tabler:separator-horizontal" width="16" height="16" />{_('Divider')}
											</button>
											<button type="button" class:active={!isHidden} aria-pressed={!isHidden} onclick={() => onToggleSidebarItemHidden(item.id)}>
												<Icon icon={isHidden ? 'tabler:eye' : 'tabler:eye-off'} width="16" height="16" />{isHidden ? _('Show') : _('Hide')}
											</button>
										</div>
									</div>
								{/if}
							{/each}
						{/if}
					</div>
				</section>
			{/each}
		</div>
	</section>

	<aside class="settings-rail sidebar-settings-summary">
		<section class="panel info-card">
			<h2>{_('Preview')}</h2>
			<ul class="sidebar-preview-list">
				{#each sidebarRootEntries as entry, entryIndex}
					<li>
						{#if entry.kind === 'group'}
							<strong>{_(sidebarGroupLabelFn(entry.group, entryIndex))}</strong>
							<span>{entry.group.items.map((item) => sidebarItemLabelFn(item)).join(', ') || _('Empty group')}</span>
						{:else}
							<strong>{_(sidebarItemLabelFn(entry.item))}</strong>
							<span>{_('Root domain')}</span>
						{/if}
					</li>
				{/each}
			</ul>
		</section>
		<section class="panel info-card">
			<h2>{_('Hidden')}</h2>
			{#if sidebarHiddenNavItems.length === 0}
				<p>{_('No domains are hidden.')}</p>
			{:else}
				<ul class="detail-list">
					{#each sidebarHiddenNavItems as item}
						<li>{item.label}<button type="button" onclick={() => onToggleSidebarItemHidden(item.id)}>{_('Show')}</button></li>
					{/each}
				</ul>
			{/if}
		</section>
		<section class="panel info-card">
			<h2>{_('Rules')}</h2>
			<ul class="detail-list">
				<li>{_('Default keeps the current sidebar order')}<em>{_('Preset')}</em></li>
				<li>{_('Communications sources stay nested')}<em>{_('Context')}</em></li>
				<li>{_('Hidden domains stay recoverable here')}<em>{_('Safe')}</em></li>
				<li>{_('Settings store no message content')}<em>{_('Privacy')}</em></li>
			</ul>
		</section>
	</aside>
</div>
