// frontend/src/domains/documents/components/DocumentsInsights.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'

const { t } = useI18n()
</script>

<template>
  <div class="widget-frame">
    <section class="panel info-card">
      <h2>{{ t('Document Insights') }}</h2>
      <p>{{ t('AI analysis results will appear here when document processing is complete.') }}</p>
    </section>
  </div>
</template>

// frontend/src/lib/pages/documents/widgets/DocumentsInsights.svelte
<script lang="ts">
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		personList: unknown[];
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { personList, isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="documents-insights" data-widget-hidden={!isWidgetVisible('documents-insights')}>
	<WidgetEditChrome widgetId="documents-insights" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<section class="panel info-card">
		<h2>{_('Document Insights')}</h2>
		<p>{_('AI analysis results will appear here when document processing is complete.')}</p>
	</section>
</div>
