// frontend/src/lib/pages/tasks/widgets/TasksDecisionObligationReview.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import * as decisionsService from '$lib/services/decisions';
	import * as obligationsService from '$lib/services/obligations';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';
	import type {
		Decision,
		DecisionEntityKind,
		DecisionReviewState,
		Obligation,
		ObligationReviewState
	} from '$lib/api';

	const _ = (key: string) => t($currentLocale, key);

	const entityKindOptions: DecisionEntityKind[] = [
		'project',
		'task',
		'persona',
		'communication',
		'document',
		'event',
		'organization',
		'knowledge'
	];

	interface Props {
		decisions: Decision[];
		obligations: Obligation[];
		entityKind: DecisionEntityKind;
		entityId: string;
		isLoading: boolean;
		error: string;
		reviewingItemId: string | null;
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		onEntityKindChange: (entityKind: DecisionEntityKind) => void;
		onEntityIdChange: (entityId: string) => void;
		onReload: () => Promise<void>;
		onReviewDecision: (
			decision: Decision,
			reviewState: Exclude<DecisionReviewState, 'suggested'>
		) => Promise<void>;
		onReviewObligation: (
			obligation: Obligation,
			reviewState: Exclude<ObligationReviewState, 'suggested'>
		) => Promise<void>;
	}

	let {
		decisions,
		obligations,
		entityKind,
		entityId,
		isLoading,
		error,
		reviewingItemId,
		isLayoutEditing,
		isWidgetVisible,
		onEntityKindChange,
		onEntityIdChange,
		onReload,
		onReviewDecision,
		onReviewObligation
	}: Props = $props();

	let hasScope = $derived(entityId.trim().length > 0);
	let reviewItemCount = $derived(decisions.length + obligations.length);

	function decisionReviewId(decision: Decision) {
		return `decision:${decision.decision_id}`;
	}

	function obligationReviewId(obligation: Obligation) {
		return `obligation:${obligation.obligation_id}`;
	}
</script>

<section
	class="widget-frame task-context-review-panel"
	class:editing={isLayoutEditing}
	data-widget-id="tasks-decision-obligation-review"
	data-widget-hidden={!isWidgetVisible('tasks-decision-obligation-review')}
	aria-busy={isLoading}
>
	<WidgetEditChrome
		widgetId="tasks-decision-obligation-review"
		{isLayoutEditing}
		isSelected={false}
		onConfigure={() => {}}
	/>
	<header>
		<div>
			<span class="panel-kicker">{_('Context')}</span>
			<h2>{_('Decision & Obligation Review')}</h2>
		</div>
		<button type="button" title={_('Reload review items')} onclick={() => void onReload()} disabled={isLoading}>
			<Icon icon="tabler:refresh" width="15" height="15" />
		</button>
	</header>

	<div class="task-context-review-scope">
		<select
			aria-label={_('Entity kind')}
			value={entityKind}
			onchange={(event) => onEntityKindChange((event.currentTarget as HTMLSelectElement).value as DecisionEntityKind)}
		>
			{#each entityKindOptions as option}
				<option value={option}>{_(option)}</option>
			{/each}
		</select>
		<input
			aria-label={_('Entity id')}
			value={entityId}
			placeholder={_('Entity id')}
			oninput={(event) => onEntityIdChange((event.currentTarget as HTMLInputElement).value)}
		/>
	</div>

	{#if error}
		<div class="task-context-review-state error">
			<span>{error}</span>
			<button type="button" onclick={() => void onReload()} disabled={isLoading}>{_('Retry')}</button>
		</div>
	{:else if isLoading}
		<div class="task-context-review-state">
			<span>{hasScope ? _('Loading review items') : _('Loading global review items')}</span>
		</div>
	{:else if reviewItemCount === 0}
		<div class="task-context-review-state">
			<span>{_('No open decisions or obligations')}</span>
		</div>
	{:else}
		<div class="task-context-review-list">
			{#each decisions as decision}
				<article class="task-context-review-item">
					<div>
						<span class="panel-kicker">{_('Decision')}</span>
						<strong>{decision.title}</strong>
						<p>{decision.rationale}</p>
						<small>{decisionsService.formatDecisionEntity(decision.decided_by_entity_kind, decision.decided_by_entity_id)} · {decisionsService.formatDecisionTime(decision.decided_at)}</small>
					</div>
					<div class="task-context-review-actions">
						<button
							type="button"
							disabled={reviewingItemId === decisionReviewId(decision)}
							onclick={() => void onReviewDecision(decision, 'user_confirmed')}
						>
							<Icon icon="tabler:check" width="14" height="14" />
							{_('Confirm')}
						</button>
						<button
							type="button"
							disabled={reviewingItemId === decisionReviewId(decision)}
							onclick={() => void onReviewDecision(decision, 'user_rejected')}
						>
							<Icon icon="tabler:x" width="14" height="14" />
							{_('Reject')}
						</button>
					</div>
				</article>
			{/each}

			{#each obligations as obligation}
				<article class="task-context-review-item">
					<div>
						<span class="panel-kicker">{_('Obligation')}</span>
						<strong>{obligation.statement}</strong>
						<p>{obligationsService.formatObligationEntity(obligation.obligated_entity_kind, obligation.obligated_entity_id)}</p>
						<small>{_(obligation.risk_state)} · {obligationsService.formatObligationDueTime(obligation.due_at)}</small>
					</div>
					<div class="task-context-review-actions">
						<button
							type="button"
							disabled={reviewingItemId === obligationReviewId(obligation)}
							onclick={() => void onReviewObligation(obligation, 'user_confirmed')}
						>
							<Icon icon="tabler:check" width="14" height="14" />
							{_('Confirm')}
						</button>
						<button
							type="button"
							disabled={reviewingItemId === obligationReviewId(obligation)}
							onclick={() => void onReviewObligation(obligation, 'user_rejected')}
						>
							<Icon icon="tabler:x" width="14" height="14" />
							{_('Reject')}
						</button>
					</div>
				</article>
			{/each}
		</div>
	{/if}
</section>

// frontend/src/domains/tasks/components/TasksDecisionObligationReview.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import type {
  Decision,
  DecisionEntityKind,
  Obligation
} from '../types/task'
import { formatDecisionTime, formatDecisionEntity, formatObligationDueTime, formatObligationEntity } from '../stores/tasks'

const { t } = useI18n()

const entityKindOptions: DecisionEntityKind[] = [
  'project', 'task', 'persona', 'communication',
  'document', 'event', 'organization', 'knowledge'
]

const props = defineProps<{
  decisions: Decision[]
  obligations: Obligation[]
  entityKind: DecisionEntityKind
  entityId: string
  isLoading: boolean
  error: string
  reviewingItemId: string | null
  onEntityKindChange: (entityKind: DecisionEntityKind) => void
  onEntityIdChange: (entityId: string) => void
  onReload: () => Promise<void>
  onReviewDecision: (decision: Decision, reviewState: 'user_confirmed' | 'user_rejected') => Promise<void>
  onReviewObligation: (obligation: Obligation, reviewState: 'user_confirmed' | 'user_rejected') => Promise<void>
}>()

const hasScope = computed(() => props.entityId.trim().length > 0)
const reviewItemCount = computed(() => props.decisions.length + props.obligations.length)

function decisionReviewId(decision: Decision): string {
  return `decision:${decision.decision_id}`
}

function obligationReviewId(obligation: Obligation): string {
  return `obligation:${obligation.obligation_id}`
}
</script>

<template>
  <section class="widget-frame task-context-review-panel" :aria-busy="props.isLoading">
    <header>
      <div>
        <span class="panel-kicker">{{ t('Context') }}</span>
        <h2>{{ t('Decision & Obligation Review') }}</h2>
      </div>
      <button type="button" :title="t('Reload review items')" @click="props.onReload" :disabled="props.isLoading">
        <Icon icon="tabler:refresh" :size="15" />
      </button>
    </header>

    <div class="task-context-review-scope">
      <select
        :aria-label="t('Entity kind')"
        :value="props.entityKind"
        @change="props.onEntityKindChange(($event.target as HTMLSelectElement).value as DecisionEntityKind)"
      >
        <option v-for="option in entityKindOptions" :key="option" :value="option">{{ t(option) }}</option>
      </select>
      <input
        :aria-label="t('Entity id')"
        :value="props.entityId"
        :placeholder="t('Entity id')"
        @input="props.onEntityIdChange(($event.target as HTMLInputElement).value)"
      />
    </div>

    <!-- Error state -->
    <div v-if="props.error" class="task-context-review-state error">
      <span>{{ props.error }}</span>
      <button type="button" @click="props.onReload" :disabled="props.isLoading">{{ t('Retry') }}</button>
    </div>

    <!-- Loading state -->
    <div v-else-if="props.isLoading" class="task-context-review-state">
      <span>{{ hasScope ? t('Loading review items') : t('Loading global review items') }}</span>
    </div>

    <!-- Empty state -->
    <div v-else-if="reviewItemCount === 0" class="task-context-review-state">
      <span>{{ t('No open decisions or obligations') }}</span>
    </div>

    <!-- Review list -->
    <div v-else class="task-context-review-list">
      <article v-for="decision in props.decisions" :key="decision.decision_id" class="task-context-review-item">
        <div>
          <span class="panel-kicker">{{ t('Decision') }}</span>
          <strong>{{ decision.title }}</strong>
          <p>{{ decision.rationale }}</p>
          <small>{{ formatDecisionEntity(decision.decided_by_entity_kind, decision.decided_by_entity_id) }} · {{ formatDecisionTime(decision.decided_at) }}</small>
        </div>
        <div class="task-context-review-actions">
          <button
            type="button"
            :disabled="props.reviewingItemId === decisionReviewId(decision)"
            @click="props.onReviewDecision(decision, 'user_confirmed')"
          >
            <Icon icon="tabler:check" :size="14" /> {{ t('Confirm') }}
          </button>
          <button
            type="button"
            :disabled="props.reviewingItemId === decisionReviewId(decision)"
            @click="props.onReviewDecision(decision, 'user_rejected')"
          >
            <Icon icon="tabler:x" :size="14" /> {{ t('Reject') }}
          </button>
        </div>
      </article>

      <article v-for="obligation in props.obligations" :key="obligation.obligation_id" class="task-context-review-item">
        <div>
          <span class="panel-kicker">{{ t('Obligation') }}</span>
          <strong>{{ obligation.statement }}</strong>
          <p>{{ formatObligationEntity(obligation.obligated_entity_kind, obligation.obligated_entity_id) }}</p>
          <small>{{ t(obligation.risk_state) }} · {{ formatObligationDueTime(obligation.due_at) }}</small>
        </div>
        <div class="task-context-review-actions">
          <button
            type="button"
            :disabled="props.reviewingItemId === obligationReviewId(obligation)"
            @click="props.onReviewObligation(obligation, 'user_confirmed')"
          >
            <Icon icon="tabler:check" :size="14" /> {{ t('Confirm') }}
          </button>
          <button
            type="button"
            :disabled="props.reviewingItemId === obligationReviewId(obligation)"
            @click="props.onReviewObligation(obligation, 'user_rejected')"
          >
            <Icon icon="tabler:x" :size="14" /> {{ t('Reject') }}
          </button>
        </div>
      </article>
    </div>
  </section>
</template>
