// frontend/src/lib/pages/timeline/widgets/TimelineFilters.svelte
<script lang="ts">
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';
	import { currentLocale, t } from '$lib/i18n';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="timeline-filters" data-widget-hidden={!isWidgetVisible('timeline-filters')}>
	<WidgetEditChrome widgetId="timeline-filters" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<section class="panel info-card"><h2>{_('Timeline Filters')}</h2>{#each ['Messages','Documents','Tasks','Calendar','Notes','Decisions'] as item}<label class="mini-check"><input type="checkbox" checked />{_(item)}</label>{/each}</section>
</div>

// frontend/src/domains/timeline/components/TimelineFilters.vue
<script setup lang="ts">
import type { TimelineFilters as TimelineFiltersType } from '../types/timeline'

interface Props {
	filters: TimelineFiltersType
}

interface Emits {
	(e: 'toggleFilter', kind: keyof TimelineFiltersType): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const filterItems: Array<keyof TimelineFiltersType> = ['Messages', 'Documents', 'Tasks', 'Calendar', 'Notes', 'Decisions']
</script>

<template>
	<section class="panel info-card">
		<h2>Timeline Filters</h2>
		<label v-for="item in filterItems" :key="item" class="mini-check">
			<input
				type="checkbox"
				:checked="filters[item]"
				@change="emit('toggleFilter', item)"
			/>
			{{ item }}
		</label>
	</section>
</template>
