// frontend/src/integrations/whatsapp/components/WhatsAppRail.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import type { WhatsappCapabilitiesResponse, WhatsappCapabilityStatus } from '../types/whatsapp'
import type { WhatsappMessageForm } from '../stores/whatsapp'

const props = defineProps<{
  whatsappCapabilities: WhatsappCapabilitiesResponse | null
  whatsappClosureCapabilities: WhatsappCapabilityStatus[]
  whatsappBlockedCapabilities: WhatsappCapabilityStatus[]
  whatsappProviderAccounts: number
  isWhatsappActionSubmitting: boolean
  openAccountDrawer: () => void
  ingestWhatsappWebMessageFixture: () => void
  whatsappMessageForm: WhatsappMessageForm
}>()

const { t } = useI18n()

function capabilityLabel(capability: string): string {
  const labels: Record<string, string> = {
    'runtime.fixture': 'Fixture Runtime',
    'sessions.manual_state': 'Session Metadata',
    'sessions.restore': 'Session Restore',
    'auth.qr_link_start': 'QR Link',
    'auth.pair_code_link_start': 'Pair-code Link',
    'sync.chats': 'Chat Sync',
    'sync.history': 'History Sync',
    'messages.read_projection': 'Message Projection Reads',
    'search.messages': 'Message Search',
    'search.media': 'Media Search',
    'media.upload_send': 'Media Upload',
    'media.download': 'Media Download',
    'messages.send_text': 'Send Text',
    'messages.reply': 'Reply',
    'messages.forward': 'Forward',
    'messages.edit': 'Edit',
    'messages.delete': 'Delete',
    'messages.react': 'React',
    'messages.unreact': 'Remove Reaction',
    'status.publish': 'Publish Status',
    'conversations.mark_read': 'Mark Read',
    'conversations.mark_unread': 'Mark Unread',
    'conversations.archive': 'Archive',
    'conversations.unarchive': 'Unarchive',
    'conversations.mute': 'Mute',
    'conversations.unmute': 'Unmute',
    'conversations.pin': 'Pin',
    'conversations.unpin': 'Unpin',
    'conversations.join_group': 'Join Group',
    'conversations.leave_group': 'Leave Group'
  }
  return labels[capability] ?? capability
}
</script>

<template>
  <aside class="stacked-rail whatsapp-rail">
    <section class="panel info-card">
      <h2>{{ t('Accounts') }}</h2>
      <div class="setup-summary-card">
        <span class="round-icon green">
          <Icon icon="tabler:brand-whatsapp" width="22" height="22" />
        </span>
        <div>
          <strong>{{ whatsappProviderAccounts }} {{ t('WhatsApp accounts') }}</strong>
          <p>
            {{ whatsappProviderAccounts
              ? t('Companion session records are available for fixture ingestion.')
              : t('No WhatsApp Web account record is configured yet.')
            }}
          </p>
        </div>
      </div>
      <div class="form-actions wide">
        <button type="button" :disabled="isWhatsappActionSubmitting" @click="openAccountDrawer">
          {{ t('Open Wizard') }}
        </button>
      </div>
    </section>

    <section class="panel info-card">
      <h2>{{ t('Runtime Guardrails') }}</h2>
      <div class="health-row">
        <span>{{ t('Mode') }}</span>
        <strong>{{ whatsappCapabilities?.runtime_mode ?? t('unknown') }}</strong>
      </div>
      <ul v-if="whatsappClosureCapabilities.length" class="detail-list">
        <li v-for="cap in whatsappClosureCapabilities" :key="cap.capability">
          {{ capabilityLabel(cap.capability) }}
          <em>{{ cap.status }}</em>
        </li>
      </ul>
      <template v-if="whatsappBlockedCapabilities.length">
        <div class="evidence-row">
          <strong>{{ t('Live Scope') }}</strong>
          <p>{{ whatsappBlockedCapabilities.map((c) => capabilityLabel(c.capability)).join(', ') }}</p>
        </div>
      </template>
      <template v-if="whatsappCapabilities?.unsupported_features?.length">
        <div class="evidence-row">
          <strong>{{ t('Unsupported') }}</strong>
          <p>{{ whatsappCapabilities.unsupported_features.map(capabilityLabel).join(', ') }}</p>
        </div>
      </template>
    </section>

    <section class="panel info-card">
      <h2>{{ t('Ingest Fixture Message') }}</h2>
      <form class="setup-form compact-form" @submit.prevent="ingestWhatsappWebMessageFixture">
        <label><span>{{ t('Account ID') }}</span><input v-model="whatsappMessageForm.account_id" autocomplete="off" /></label>
        <label><span>{{ t('Chat ID') }}</span><input v-model="whatsappMessageForm.provider_chat_id" autocomplete="off" /></label>
        <label><span>{{ t('Chat title') }}</span><input v-model="whatsappMessageForm.chat_title" autocomplete="off" /></label>
        <label><span>{{ t('Sender ID') }}</span><input v-model="whatsappMessageForm.sender_id" autocomplete="off" /></label>
        <label><span>{{ t('Sender') }}</span><input v-model="whatsappMessageForm.sender_display_name" autocomplete="off" /></label>
        <label class="wide"><span>{{ t('Text') }}</span><textarea v-model="whatsappMessageForm.text" rows="3"></textarea></label>
        <div class="form-actions wide">
          <button type="submit" :disabled="isWhatsappActionSubmitting || !whatsappMessageForm.text.trim()">
            {{ t('Ingest Fixture') }}
          </button>
        </div>
      </form>
    </section>
  </aside>
</template>

// frontend/src/lib/pages/whatsapp/widgets/WhatsAppRail.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		whatsappClosureCapabilities: unknown[];
		whatsappBlockedCapabilities: unknown[];
		whatsappCapabilities: unknown | null;
		whatsappProviderAccounts: unknown[];
		isWhatsappActionSubmitting: boolean;
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		capabilityLabel: (capability: string) => string;
		openAccountDrawer: (target: string) => void;
		ingestWhatsappWebMessageFixture: () => Promise<void>;
		whatsappMessageForm: { account_id: string; provider_chat_id: string; chat_title: string; sender_id: string; sender_display_name: string; text: string };
	}

	let {
		whatsappClosureCapabilities,
		whatsappBlockedCapabilities,
		whatsappCapabilities,
		whatsappProviderAccounts,
		isWhatsappActionSubmitting,
		isLayoutEditing,
		isWidgetVisible,
		capabilityLabel,
		openAccountDrawer,
		ingestWhatsappWebMessageFixture,
		whatsappMessageForm
	}: Props = $props();
</script>

<aside class="stacked-rail whatsapp-rail">
	<div class="widget-frame stacked-rail" class:editing={isLayoutEditing} data-widget-id="whatsapp-sync-controls" data-widget-hidden={!isWidgetVisible('whatsapp-sync-controls')}>
		<WidgetEditChrome widgetId="whatsapp-sync-controls" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
		<section class="panel info-card">
			<h2>{_('Account Setup')}</h2>
			<div class="setup-summary-card">
				<span class="round-icon green"><Icon icon="tabler:brand-whatsapp" width="22" height="22" /></span>
				<div>
					<strong>{whatsappProviderAccounts.length} {_('WhatsApp accounts')}</strong>
					<p>{whatsappProviderAccounts.length ? _('Companion session records are available for fixture ingestion.') : _('No WhatsApp Web account record is configured yet.')}</p>
				</div>
			</div>
			<div class="form-actions wide">
				<button type="button" onclick={() => openAccountDrawer('whatsapp')} disabled={isWhatsappActionSubmitting}>{_('Open Wizard')}</button>
			</div>
		</section>

		<section class="panel info-card">
			<h2>{_('Runtime Guardrails')}</h2>
			<div class="health-row"><span>{_('Mode')}</span><strong>{(whatsappCapabilities as Record<string, unknown>)?.runtime_mode ?? _('unknown') as string}</strong></div>
			{#if whatsappClosureCapabilities.length}
				<ul class="detail-list">
					{#each whatsappClosureCapabilities as capability}
						<li>{capabilityLabel((capability as Record<string, unknown>).capability as string)}<em>{(capability as Record<string, unknown>).status as string}</em></li>
					{/each}
				</ul>
			{:else}
				<p>{_('Capability contract is not loaded yet.')}</p>
			{/if}
			{#if whatsappBlockedCapabilities.length}
				<div class="evidence-row">
					<strong>{_('Live Scope')}</strong>
					<p>{whatsappBlockedCapabilities.map((capability) => capabilityLabel((capability as Record<string, unknown>).capability as string)).join(', ')}</p>
				</div>
			{/if}
			{#if (whatsappCapabilities as Record<string, unknown>)?.unsupported_features && ((whatsappCapabilities as Record<string, unknown>).unsupported_features as unknown[]).length}
				<div class="evidence-row">
					<strong>{_('Unsupported')}</strong>
					<p>{((whatsappCapabilities as Record<string, unknown>).unsupported_features as unknown[]).map(capabilityLabel as unknown as (f: unknown) => string).join(', ')}</p>
				</div>
			{/if}
		</section>

		<section class="panel info-card">
			<h2>{_('Fixture Message')}</h2>
			<form class="setup-form compact-form" onsubmit={(event) => { event.preventDefault(); void ingestWhatsappWebMessageFixture(); }}>
				<label><span>{_('Account ID')}</span><input bind:value={whatsappMessageForm.account_id} autocomplete="off" /></label>
				<label><span>{_('Chat ID')}</span><input bind:value={whatsappMessageForm.provider_chat_id} autocomplete="off" /></label>
				<label><span>{_('Chat title')}</span><input bind:value={whatsappMessageForm.chat_title} autocomplete="off" /></label>
				<label><span>{_('Sender ID')}</span><input bind:value={whatsappMessageForm.sender_id} autocomplete="off" /></label>
				<label><span>{_('Sender')}</span><input bind:value={whatsappMessageForm.sender_display_name} autocomplete="off" /></label>
				<label class="wide"><span>{_('Text')}</span><textarea bind:value={whatsappMessageForm.text} rows="3"></textarea></label>
				<div class="form-actions wide"><button type="submit" disabled={isWhatsappActionSubmitting || !whatsappMessageForm.text.trim()}>{_('Ingest Fixture')}</button></div>
			</form>
		</section>
	</div>
</aside>
