// frontend/src/domains/calendar/views/CalendarPage.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useI18n } from '../../../platform/i18n'
import CalendarToolbar from '../components/CalendarToolbar.vue'
import CalendarWeekGrid from '../components/CalendarWeekGrid.vue'
import CalendarUpcoming from '../components/CalendarUpcoming.vue'
import CalendarSourceStatus from '../components/CalendarSourceStatus.vue'
import {
  useCalendarEventsQuery,
  useCalendarAccountsQuery
} from '../queries/useCalendarEventsQuery'
import { useCalendarStore, getWeekStart, getWeekColumns, filterWeekEvents, formatEventDateTime, eventTypeLabel } from '../stores/calendar'
import {
  fetchCalendarSources,
  fetchWeeklyBrief,
  fetchEventBrief,
  fetchEventAgenda,
  searchCalendarEvents,
  createCalendarEvent,
  fetchEventContextPack
} from '../api/calendar'
import Icon from '../../../shared/ui/Icon.vue'
import Button from '../../../shared/ui/Button.vue'
import type { CalendarEvent, CalendarSource, WeeklyBrief } from '../types/calendar'

const { t } = useI18n()
const store = useCalendarStore()

// TanStack Query data
const { data: accountsData, isLoading: isAccountsLoading } = useCalendarAccountsQuery()
const { data: eventsData, isLoading: isEventsLoading, refetch: refetchEvents } = useCalendarEventsQuery(200)

const calendarAccounts = computed(() => accountsData.value ?? [])
const calendarEvents = computed(() => eventsData.value ?? [])

// Calendar sources loaded manually (depends on accounts)
const calendarSources = ref<CalendarSource[]>([])

// Search results
const searchResults = ref<CalendarEvent[]>([])

// Week calculation
const weekStart = ref(getWeekStart())
const weekColumns = computed(() => getWeekColumns(weekStart.value))
const filteredEvents = computed(() => filterWeekEvents(calendarEvents.value, weekStart.value))

// Event detail state
const eventContext = ref<Record<string, unknown> | null>(null)

// Derived
const isLoading = computed(() => isAccountsLoading || isEventsLoading)
const displayEvents = computed(() =>
  searchResults.value.length > 0 ? searchResults.value : filteredEvents.value
)

async function loadSources() {
  const results: CalendarSource[] = []
  for (const acct of calendarAccounts.value) {
    try {
      const res = await fetchCalendarSources(acct.account_id)
      results.push(...res.items)
    } catch (_) { /* sources optional */ }
  }
  calendarSources.value = results
}

async function loadWeeklyBrief() {
  try {
    const brief = await fetchWeeklyBrief()
    store.setWeeklyBrief(brief as unknown as WeeklyBrief)
  } catch (_) {
    store.setWeeklyBrief(null)
  }
}

async function handleSearch() {
  if (!store.searchQuery.trim()) {
    searchResults.value = []
    return
  }
  try {
    const res = await searchCalendarEvents(store.searchQuery)
    searchResults.value = (res.results as CalendarEvent[]) || []
  } catch (_) {
    searchResults.value = []
  }
}

async function handlePrepareEvent(evt: CalendarEvent) {
  store.selectEvent(evt)
  try {
    const [ctx, brief, agenda] = await Promise.all([
      fetchEventContextPack(evt.event_id),
      fetchEventBrief(evt.event_id),
      fetchEventAgenda(evt.event_id)
    ])
    eventContext.value = ctx as unknown as Record<string, unknown>
    store.setEventBrief(brief)
    store.setEventAgenda(agenda as unknown as Record<string, unknown> | null)
  } catch (_) {
    eventContext.value = null
    store.setEventBrief(null)
    store.setEventAgenda(null)
  }
}

async function handleCreateEvent() {
  if (!store.newEventTitle || !store.newEventStart || !store.newEventEnd) return
  try {
    await createCalendarEvent({
      title: store.newEventTitle,
      start_at: new Date(store.newEventStart).toISOString(),
      end_at: new Date(store.newEventEnd).toISOString(),
      event_type: store.newEventType
    })
    store.resetNewEventForm()
    refetchEvents()
  } catch (e) {
    store.setCalendarError(e instanceof Error ? e.message : 'Create failed')
  }
}

async function handleRefreshAll() {
  refetchEvents()
  loadSources()
  loadWeeklyBrief()
}

onMounted(() => {
  loadSources()
  loadWeeklyBrief()
})
</script>

<template>
  <section class="calendar-page">
    <CalendarToolbar
      @search-calendar="handleSearch"
      @load-calendar="refetchEvents"
      @load-weekly-brief="loadWeeklyBrief"
      @refresh-all="handleRefreshAll"
    />

    <!-- New Event Form -->
    <div v-if="store.showNewEventForm" class="panel new-event-form">
      <h3>{{ t('New Event') }}</h3>
      <div class="form-row">
        <input
          type="text"
          :placeholder="t('Event title')"
          v-model="store.newEventTitle"
        />
        <select v-model="store.newEventType">
          <option
            v-for="opt in ['meeting', 'focus', 'deadline', 'personal', 'travel', 'tax', 'review', 'planning']"
            :key="opt"
            :value="opt"
          >{{ eventTypeLabel(opt) }}</option>
        </select>
      </div>
      <div class="form-row">
        <input type="datetime-local" v-model="store.newEventStart" />
        <span>&rarr;</span>
        <input type="datetime-local" v-model="store.newEventEnd" />
      </div>
      <div class="form-actions">
        <Button variant="default" @click="handleCreateEvent">{{ t('Create') }}</Button>
        <Button variant="ghost" @click="store.resetNewEventForm()">{{ t('Cancel') }}</Button>
      </div>
    </div>

    <!-- Filter bar -->
    <div class="filter-bar">
      <span>{{ calendarAccounts.length }} {{ t('accounts') }} &middot; {{ calendarEvents.length }} {{ t('events') }}</span>
      <span v-if="store.calendarError" class="error-text">{{ store.calendarError }}</span>
      <span v-if="searchResults.length > 0" class="search-hint">
        {{ t('Search') }}: {{ searchResults.length }} {{ t('results for') }} "{{ store.searchQuery }}"
      </span>
    </div>

    <!-- Main layout -->
    <div class="calendar-layout">
      <CalendarWeekGrid
        :week-columns="weekColumns"
        :calendar-search-results="searchResults"
        :filtered-events="filteredEvents"
        :is-calendar-loading="isAccountsLoading || isEventsLoading"
        :calendar-accounts="calendarAccounts"
        :selected-event="store.selectedEvent"
        :on-prepare-event="handlePrepareEvent"
      />
      <aside class="stacked-rail">
        <!-- Weekly Brief -->
        <div class="panel info-card">
          <h2>
            {{ t('Weekly Brief') }}
            <Button variant="ghost" size="sm" @click="loadWeeklyBrief">
              <Icon icon="tabler:refresh" :size="12" />
            </Button>
          </h2>
          <template v-if="store.weeklyBrief">
            <div class="metric-grid tiny">
              <article class="metric-card">
                <span>{{ t('Events') }}</span>
                <strong>{{ store.weeklyBrief.upcoming_events_this_week || 0 }}</strong>
              </article>
              <article class="metric-card">
                <span>{{ t('Overdue') }}</span>
                <strong>{{ store.weeklyBrief.overdue_deadlines || 0 }}</strong>
              </article>
              <article class="metric-card">
                <span>{{ t('No Notes') }}</span>
                <strong>{{ store.weeklyBrief.past_events_without_notes || 0 }}</strong>
              </article>
            </div>
          </template>
          <p v-else class="muted">{{ t('Click refresh to load') }}</p>
        </div>

        <CalendarUpcoming
          :calendar-events="calendarEvents"
          @prepare-event="handlePrepareEvent"
        />

        <!-- Event Detail -->
        <div v-if="store.selectedEvent" class="panel info-card event-detail">
          <h2>
            {{ store.selectedEvent.title }}
            <Button variant="ghost" size="sm" @click="store.selectEvent(null)">
              <Icon icon="tabler:x" :size="14" />
            </Button>
          </h2>
          <div class="event-meta">
            <span><Icon icon="tabler:clock" :size="14" /> {{ formatEventDateTime(store.selectedEvent.start_at) }}</span>
            <span v-if="store.selectedEvent.location">
              <Icon icon="tabler:map-pin" :size="14" /> {{ store.selectedEvent.location }}
            </span>
            <span :class="['chip', store.selectedEvent.status]">{{ store.selectedEvent.status }}</span>
          </div>
          <div v-if="store.eventBrief" class="brief-section">
            <h4>{{ t('Brief') }}</h4>
            <div v-if="(store.eventBrief.participants as any[])?.length" class="brief-participants">
              <span
                v-for="(p, idx) in (store.eventBrief.participants as any[])"
                :key="idx"
                class="participant-chip"
              >{{ p.name || p.email }}</span>
            </div>
            <p v-if="(store.eventBrief.context as any)?.summary" class="muted">
              {{ (store.eventBrief.context as any).summary }}
            </p>
          </div>
          <div v-if="store.eventAgenda" class="brief-section">
            <h4>{{ t('Agenda') }}</h4>
            <ul v-if="store.eventAgenda.suggested_agenda" class="agenda-list">
              <li v-for="(item, idx) in store.eventAgenda.suggested_agenda" :key="idx">{{ item }}</li>
            </ul>
          </div>
          <div class="event-actions">
            <Button variant="default" size="sm" @click="store.selectedEvent && handlePrepareEvent(store.selectedEvent)">
              <Icon icon="tabler:brain" :size="14" /> {{ t('Prepare') }}
            </Button>
            <Button variant="ghost" size="sm" @click="store.selectEvent(null)">
              <Icon icon="tabler:check" :size="14" /> {{ t('Complete') }}
            </Button>
          </div>
        </div>

        <CalendarSourceStatus
          :calendar-sources="calendarSources"
          :calendar-accounts="calendarAccounts"
        />
      </aside>
    </div>
  </section>
</template>

// frontend/src/lib/pages/calendar/CalendarPage.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import * as calendarService from '$lib/services/calendar';
	import type { CalendarAccount, CalendarEvent, CalendarSource } from '$lib/api';
	import CalendarToolbar from './widgets/CalendarToolbar.svelte';
	import CalendarWeekGrid from './widgets/CalendarWeekGrid.svelte';
	import CalendarUpcoming from './widgets/CalendarUpcoming.svelte';
	import CalendarSourceStatus from './widgets/CalendarSourceStatus.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();

	let calendarAccounts = $state<CalendarAccount[]>([]);
	let calendarEvents = $state<CalendarEvent[]>([]);
	let calendarSources = $state<CalendarSource[]>([]);
	let calendarError = $state('');
	let isCalendarLoading = $state(false);
	let calendarViewMode = $state<'day' | 'week' | 'month' | 'agenda'>('week');
	let calendarSearchQuery = $state('');
	let calendarSearchResults = $state<CalendarEvent[]>([]);
	let selectedEvent = $state<CalendarEvent | null>(null);
	let weeklyBrief = $state<Record<string, unknown> | null>(null);
	let eventBrief = $state<Record<string, unknown> | null>(null);
	let eventAgenda = $state<Record<string, unknown> | null>(null);
	let showNewEventForm = $state(false);
	let newEventTitle = $state('');
	let newEventStart = $state('');
	let newEventEnd = $state('');
	let newEventType = $state('meeting');

	const weekDays = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
	const nowDate = new Date();
	const weekStart = new Date(nowDate);
	weekStart.setDate(nowDate.getDate() - nowDate.getDay() + 1);
	weekStart.setHours(0, 0, 0, 0);
	const weekColumns = weekDays.map((d, i) => {
		const d2 = new Date(weekStart); d2.setDate(weekStart.getDate() + i);
		return `${d} ${d2.getDate()}`;
	});

	let filteredEvents = $derived(calendarEvents.filter(e => {
		const start = new Date(e.start_at);
		const end = new Date(weekStart); end.setDate(weekStart.getDate() + 7);
		return start >= weekStart && start < end;
	}));

	async function loadCalendar() {
		isCalendarLoading = true;
		const result = await calendarService.loadCalendar();
		calendarAccounts = result.accounts;
		calendarEvents = result.events;
		calendarSources = result.sources;
		calendarError = result.error;
		isCalendarLoading = false;
	}

	async function loadWeeklyBrief() {
		const result = await calendarService.loadWeeklyBrief();
		weeklyBrief = result.brief;
	}

	async function searchCalendar() {
		const result = await calendarService.searchCalendar(calendarSearchQuery);
		calendarSearchResults = result.results;
	}

	async function prepareEvent(evt: CalendarEvent) {
		selectedEvent = evt;
		const result = await calendarService.prepareEvent(evt);
		eventBrief = result.brief;
		eventAgenda = result.agenda;
	}

	async function completeEvent(evt: CalendarEvent) {
		selectedEvent = evt;
		await calendarService.completeEvent(evt);
	}

	async function handleCreateEvent() {
		const result = await calendarService.handleCreateEvent(newEventTitle, newEventStart, newEventEnd, newEventType);
		if (result.error) { calendarError = result.error; return; }
		showNewEventForm = false;
		newEventTitle = '';
		await loadCalendar();
	}

	$effect(() => {
		loadCalendar();
	});
</script>

<section class="calendar-page">
	<CalendarToolbar
		activeViewTitle="Calendar"
		activeViewSubtitle="All your events from connected calendars"
		{calendarViewMode}
		{calendarSearchQuery}
		{isLayoutEditing}
		{isWidgetVisible}
		onCalendarViewMode={(mode) => { calendarViewMode = mode as 'day' | 'week' | 'month' | 'agenda'; loadCalendar(); }}
		onSearchCalendar={searchCalendar}
		onToggleNewEventForm={() => (showNewEventForm = !showNewEventForm)}
		onOpenAccountDrawer={() => {}}
		onLoadCalendar={loadCalendar}
		onLoadWeeklyBrief={loadWeeklyBrief}
	/>

	{#if showNewEventForm}
		<div class="panel new-event-form">
			<h3>New Event</h3>
			<div class="form-row">
				<input type="text" placeholder="Event title" bind:value={newEventTitle} />
				<select bind:value={newEventType}>
					<option value="meeting">Meeting</option><option value="focus">Focus</option>
					<option value="deadline">Deadline</option><option value="personal">Personal</option>
					<option value="travel">Travel</option><option value="tax">Tax</option>
					<option value="review">Review</option><option value="planning">Planning</option>
				</select>
			</div>
			<div class="form-row"><input type="datetime-local" bind:value={newEventStart} /><span>→</span><input type="datetime-local" bind:value={newEventEnd} /></div>
			<div class="form-actions"><button type="button" class="primary-button" onclick={handleCreateEvent}>Create</button><button type="button" class="ghost-button" onclick={() => (showNewEventForm = false)}>Cancel</button></div>
		</div>
	{/if}

	<div class="filter-bar">
		<span>{calendarAccounts.length} accounts &middot; {calendarEvents.length} events</span>
		{#if calendarError}<span class="error-text">{calendarError}</span>{/if}
		{#if calendarSearchResults.length > 0}<span class="search-hint">Search: {calendarSearchResults.length} results for "{calendarSearchQuery}"</span>{/if}
	</div>

	<div class="calendar-layout">
		<CalendarWeekGrid
			{weekColumns}
			{calendarSearchResults}
			{filteredEvents}
			{isCalendarLoading}
			{calendarAccounts}
			{isLayoutEditing}
			{isWidgetVisible}
			onPrepareEvent={prepareEvent}
		/>
		<aside class="stacked-rail">
			<div class="panel info-card">
				<h2>Weekly Brief <button type="button" class="link-row" onclick={loadWeeklyBrief}><Icon icon="tabler:refresh" width="12" height="12" /></button></h2>
				{#if weeklyBrief}
					<div class="metric-grid tiny">
						<article class="metric-card"><span>Events</span><strong>{weeklyBrief.upcoming_events_this_week as number || 0}</strong></article>
						<article class="metric-card"><span>Overdue</span><strong>{weeklyBrief.overdue_deadlines as number || 0}</strong></article>
						<article class="metric-card"><span>No Notes</span><strong>{weeklyBrief.past_events_without_notes as number || 0}</strong></article>
					</div>
				{:else}<p class="muted">Click refresh to load</p>{/if}
			</div>
			<CalendarUpcoming {calendarEvents} {isLayoutEditing} {isWidgetVisible} onPrepareEvent={prepareEvent} />
			{#if selectedEvent}
				<div class="panel info-card event-detail">
					<h2>{selectedEvent.title} <button type="button" class="ghost-button small" onclick={() => { selectedEvent = null; eventBrief = null; eventAgenda = null; }}><Icon icon="tabler:x" width="14" height="14" /></button></h2>
					<div class="event-meta">
						<span><Icon icon="tabler:clock" width="14" height="14" /> {new Date(selectedEvent.start_at).toLocaleString()}</span>
						{#if selectedEvent.location}<span><Icon icon="tabler:map-pin" width="14" height="14" /> {selectedEvent.location}</span>{/if}
						<span class="chip {selectedEvent.status}">{selectedEvent.status}</span>
					</div>
					{#if eventBrief}
						<div class="brief-section"><h4>Brief</h4>
							{#if (eventBrief.participants as any[])}<div class="brief-participants">{#each (eventBrief.participants as any[]) as p}<span class="participant-chip">{p.name || p.email}</span>{/each}</div>{/if}
							{#if (eventBrief.context as any)?.summary}<p class="muted">{(eventBrief.context as any).summary}</p>{/if}
						</div>
					{/if}
					{#if eventAgenda}
						<div class="brief-section"><h4>Agenda</h4>
							{#if eventAgenda.suggested_agenda}<ul class="agenda-list">{#each (eventAgenda.suggested_agenda as any[]) as item}<li>{item}</li>{/each}</ul>{/if}
						</div>
					{/if}
					<div class="event-actions">
						<button type="button" class="primary-button small" onclick={() => selectedEvent && prepareEvent(selectedEvent)}><Icon icon="tabler:brain" width="14" height="14" /> Prepare</button>
						<button type="button" class="ghost-button small" onclick={() => selectedEvent && completeEvent(selectedEvent)}><Icon icon="tabler:check" width="14" height="14" /> Complete</button>
					</div>
				</div>
			{/if}
			<CalendarSourceStatus {calendarSources} {calendarAccounts} {isLayoutEditing} {isWidgetVisible} />
		</aside>
	</div>
</section>
