// frontend/src/lib/pages/calendar/widgets/CalendarToolbar.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		activeViewTitle: string;
		activeViewSubtitle: string;
		calendarViewMode: string;
		calendarSearchQuery: string;
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		onCalendarViewMode: (mode: string) => void;
		onSearchCalendar: () => void;
		onToggleNewEventForm: () => void;
		onOpenAccountDrawer: () => void;
		onLoadCalendar: () => void;
		onLoadWeeklyBrief: () => void;
	}

	let {
		activeViewTitle, activeViewSubtitle, calendarViewMode, calendarSearchQuery,
		isLayoutEditing, isWidgetVisible,
		onCalendarViewMode, onSearchCalendar, onToggleNewEventForm,
		onOpenAccountDrawer, onLoadCalendar, onLoadWeeklyBrief
	}: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="calendar-toolbar" data-widget-hidden={!isWidgetVisible('calendar-toolbar')}>
	<WidgetEditChrome widgetId="calendar-toolbar" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<div class="view-header">
		<div class="view-title-with-icon">
			<span class="hero-mark small"><Icon icon="tabler:calendar" width="28" height="28" /></span>
			<div><h1>{_(activeViewTitle)}</h1><p>{_(activeViewSubtitle)}</p></div>
		</div>
		<div class="search-bar">
			<input type="text" placeholder="Search events..." bind:value={calendarSearchQuery} oninput={() => onSearchCalendar()} />
		</div>
		<div class="section-tabs pill-tabs">
			<button type="button" class:active={calendarViewMode === 'day'} onclick={() => onCalendarViewMode('day')}>Day</button>
			<button type="button" class:active={calendarViewMode === 'week'} onclick={() => onCalendarViewMode('week')}>Week</button>
			<button type="button" class:active={calendarViewMode === 'month'} onclick={() => onCalendarViewMode('month')}>Month</button>
			<button type="button" class:active={calendarViewMode === 'agenda'} onclick={() => onCalendarViewMode('agenda')}>Agenda</button>
		</div>
		<button type="button" class="primary-button" onclick={onToggleNewEventForm}><Icon icon="tabler:plus" width="16" height="16" /> New Event</button>
		<button type="button" class="ghost-button" onclick={onOpenAccountDrawer}><Icon icon="tabler:calendar-plus" width="16" height="16" />Add Calendar</button>
		<button type="button" class="ghost-button" onclick={() => { onLoadCalendar(); onLoadWeeklyBrief(); }} title="Refresh"><Icon icon="tabler:refresh" width="16" height="16" /></button>
	</div>
</div>

// frontend/src/domains/calendar/components/CalendarToolbar.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'
import { useCalendarStore } from '../stores/calendar'
import type { CalendarViewMode } from '../types/calendar'

const { t } = useI18n()
const store = useCalendarStore()

const emit = defineEmits<{
  (e: 'search-calendar'): void
  (e: 'load-calendar'): void
  (e: 'load-weekly-brief'): void
  (e: 'refresh-all'): void
}>()

function setMode(mode: CalendarViewMode) {
  store.setViewMode(mode)
}
</script>

<template>
  <div class="widget-frame">
    <div class="view-header">
      <div class="view-title-with-icon">
        <span class="hero-mark small"><Icon icon="tabler:calendar" :size="28" /></span>
        <div>
          <h1>{{ t('Calendar') }}</h1>
          <p>{{ t('All your events from connected calendars') }}</p>
        </div>
      </div>
      <div class="search-bar">
        <input
          type="text"
          :placeholder="t('Search events...')"
          :value="store.searchQuery"
          @input="store.setSearchQuery(($event.target as HTMLInputElement).value); emit('search-calendar')"
        />
      </div>
      <div class="section-tabs pill-tabs">
        <button
          v-for="mode in (['day', 'week', 'month', 'agenda'] as CalendarViewMode[])"
          :key="mode"
          type="button"
          :class="['pill-tab', { active: store.viewMode === mode }]"
          @click="setMode(mode)"
        >{{ t(mode.charAt(0).toUpperCase() + mode.slice(1)) }}</button>
      </div>
      <button type="button" class="primary-button" @click="store.toggleNewEventForm()">
        <Icon icon="tabler:plus" :size="16" /> {{ t('New Event') }}
      </button>
      <button type="button" class="ghost-button" @click="emit('refresh-all')" :title="t('Refresh')">
        <Icon icon="tabler:refresh" :size="16" />
      </button>
    </div>
  </div>
</template>
