// frontend/src/domains/calendar/components/CalendarWeekGrid.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import type { CalendarEvent, CalendarAccount } from '../types/calendar'
import { eventTypeTone, formatEventTime, formatEventDayShort } from '../stores/calendar'

const { t } = useI18n()

const props = defineProps<{
  weekColumns: string[]
  calendarSearchResults: CalendarEvent[]
  filteredEvents: CalendarEvent[]
  isCalendarLoading: boolean
  calendarAccounts: CalendarAccount[]
  selectedEvent: CalendarEvent | null
  onPrepareEvent: (evt: CalendarEvent) => void
}>()

function handleEventClick(evt: CalendarEvent) {
  props.onPrepareEvent(evt)
}
</script>

<template>
  <section class="panel week-board">
    <div class="week-header">
      <strong v-for="(day, i) in weekColumns" :key="i">{{ day }}</strong>
    </div>
    <div class="event-list">
      <div v-if="isCalendarLoading" class="loading-state">{{ t('Loading events...') }}</div>
      <div
        v-else-if="(calendarSearchResults.length > 0 ? calendarSearchResults : filteredEvents).length === 0"
        class="empty-state"
      >{{ t('No events') }}</div>
      <template v-else>
        <div
          v-for="evt in (calendarSearchResults.length > 0 ? calendarSearchResults : filteredEvents)"
          :key="evt.event_id"
          :class="['event-row', eventTypeTone(evt.event_type)]"
          role="button"
          tabindex="0"
          @click="handleEventClick(evt)"
          @keydown.enter="handleEventClick(evt)"
        >
          <span class="event-day">{{ formatEventDayShort(evt.start_at) }}</span>
          <span class="event-time">
            {{ formatEventTime(evt.start_at) }} - {{ formatEventTime(evt.end_at) }}
          </span>
          <strong>{{ evt.title }}</strong>
          <span class="event-type-chip">{{ evt.event_type || t('event') }}</span>
          <em v-if="evt.importance_score && evt.importance_score > 0.5" class="importance-dot high"></em>
          <em v-if="evt.readiness_score != null && evt.readiness_score < 0.5" class="importance-dot warn"></em>
        </div>
      </template>
    </div>
    <footer class="source-footer">
      <span v-for="acct in calendarAccounts" :key="acct.account_id" class="source-badge">{{ acct.account_name }}</span>
    </footer>
  </section>
</template>

// frontend/src/lib/pages/calendar/widgets/CalendarWeekGrid.svelte
<script lang="ts">
	import { currentLocale, t } from '$lib/i18n';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';
	import type { CalendarAccount, CalendarEvent } from '$lib/api';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		weekColumns: string[];
		calendarSearchResults: CalendarEvent[];
		filteredEvents: CalendarEvent[];
		isCalendarLoading: boolean;
		calendarAccounts: CalendarAccount[];
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
		onPrepareEvent: (evt: CalendarEvent) => void;
	}

	let { weekColumns, calendarSearchResults, filteredEvents, isCalendarLoading, calendarAccounts, isLayoutEditing, isWidgetVisible, onPrepareEvent }: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="calendar-week-grid" data-widget-hidden={!isWidgetVisible('calendar-week-grid')}>
	<WidgetEditChrome widgetId="calendar-week-grid" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<section class="panel week-board">
		<div class="week-header">
			{#each weekColumns as day}
				<strong>{day}</strong>
			{/each}
		</div>
		<div class="event-list">
			{#if isCalendarLoading}
				<div class="loading-state">{_('Loading events...')}</div>
			{:else if (calendarSearchResults.length > 0 ? calendarSearchResults : filteredEvents).length === 0}
				<div class="empty-state">{_('No events')}</div>
			{:else}
				{#each (calendarSearchResults.length > 0 ? calendarSearchResults : filteredEvents) as evt (evt.event_id)}
					{@const tone = evt.event_type === 'meeting' ? 'blue' : evt.event_type === 'deadline' ? 'red' : evt.event_type === 'focus' ? 'green' : 'neutral'}
					{@const dayLabel = new Date(evt.start_at).toLocaleDateString('en-US', {weekday:'short', day:'numeric'})}
					<div class="event-row {tone}" onclick={() => onPrepareEvent(evt)} role="button" tabindex="0" onkeydown={(e) => e.key === 'Enter' && onPrepareEvent(evt)}>
						<span class="event-day">{dayLabel}</span>
						<span class="event-time">{new Date(evt.start_at).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})} - {new Date(evt.end_at).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</span>
						<strong>{evt.title}</strong>
						<span class="event-type-chip">{evt.event_type || _('event')}</span>
						{#if evt.importance_score && evt.importance_score > 0.5}<em class="importance-dot high"></em>{/if}
						{#if evt.readiness_score != null && evt.readiness_score < 0.5}<em class="importance-dot warn"></em>{/if}
					</div>
				{/each}
			{/if}
		</div>
		<footer class="source-footer">
			{#each calendarAccounts as acct}
				<span class="source-badge">{acct.account_name}</span>
			{/each}
		</footer>
	</section>
</div>
