// frontend/src/lib/pages/documents/widgets/DocumentsSourceCards.svelte
<script lang="ts">
	import { currentLocale, t } from '$lib/i18n';
	import Icon from '@iconify/svelte';
	import WidgetEditChrome from '$lib/components/shared/WidgetEditChrome.svelte';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();
</script>

<div class="widget-frame" class:editing={isLayoutEditing} data-widget-id="documents-source-cards" data-widget-hidden={!isWidgetVisible('documents-source-cards')}>
	<WidgetEditChrome widgetId="documents-source-cards" {isLayoutEditing} isSelected={false} onConfigure={() => {}} />
	<div class="document-source-cards">
		{#each ['Google Drive 1,243', 'OneDrive 812', 'Dropbox 342', 'Notion 256'] as source, index}
			<div class="source-card">
				<span class="round-icon"><Icon icon={['tabler:brand-google-drive','tabler:brand-office','tabler:brand-dropbox','tabler:brand-notion'][index]} width="24" height="24" /></span>
				<strong>{_(source.split(' ')[0])}</strong>
				<em>{source.split(' ')[1]}</em>
			</div>
		{/each}
	</div>
</div>

// frontend/src/domains/documents/components/DocumentsSourceCards.vue
<script setup lang="ts">
import { useI18n } from '../../../platform/i18n'
import Icon from '../../../shared/ui/Icon.vue'

const { t } = useI18n()

const sources = [
  { name: 'Google Drive', count: '1,243', icon: 'tabler:brand-google-drive' },
  { name: 'OneDrive', count: '812', icon: 'tabler:brand-office' },
  { name: 'Dropbox', count: '342', icon: 'tabler:brand-dropbox' },
  { name: 'Notion', count: '256', icon: 'tabler:brand-notion' }
]
</script>

<template>
  <div class="widget-frame documents-source-cards-panel">
    <div class="document-source-cards">
      <div v-for="src in sources" :key="src.name" class="source-card">
        <span class="round-icon">
          <Icon :icon="src.icon" :size="24" />
        </span>
        <strong>{{ t(src.name) }}</strong>
        <em>{{ src.count }}</em>
      </div>
    </div>
  </div>
</template>
