// frontend/src/lib/components/shell/NotificationsDrawer.svelte
<script lang="ts">
	import './notifications.css';
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import {
		isNotificationsDrawerOpen,
		closeNotificationsDrawer,
		dismissNotification,
		toggleNotificationExpanded,
		isNotificationExpanded,
		expandedNotificationIds
	} from '$lib/stores/notifications';

	const _ = (key: string) => t($currentLocale, key);

	type NotificationItem = {
		id: string;
		source: string;
		icon: string;
		title: string;
		body: string;
		meta: string;
		time: string | null;
		messageId?: string;
		accountId?: string;
		providerChatId?: string | null;
		targetSection?: string;
		isDemo?: boolean;
	};

	interface Props {
		notificationItems: NotificationItem[];
		onOpenTarget: (notification: Record<string, unknown>) => void | Promise<void>;
		formatDateTime: (value: string | null) => string;
	}

	let { notificationItems, onOpenTarget, formatDateTime }: Props = $props();

	function notificationNeedsExpansion(notification: { body: string }) {
		return notification.body.length > 120;
	}
</script>

{#if $isNotificationsDrawerOpen}
	<button
		type="button"
		class="notifications-backdrop"
		aria-label="Close notifications"
		onclick={closeNotificationsDrawer}
	></button>
	<aside id="notifications-drawer" class="notifications-drawer" aria-label="Notifications">
		<header>
			<div>
				<h2>{_('Notifications')}</h2>
				<p>{notificationItems.length} active</p>
			</div>
			<button type="button" class="icon-button" aria-label="Close notifications" onclick={closeNotificationsDrawer}>
				<Icon icon="tabler:x" width="18" height="18" />
			</button>
		</header>
		{#if notificationItems.length === 0}
			<div class="notifications-empty">
				<Icon icon="tabler:bell-check" width="28" height="28" />
				<p>{_('No active notifications.')}</p>
			</div>
		{:else}
			<div class="notifications-list">
				{#each notificationItems as notification}
					<article>
						<button
							type="button"
							class="notification-target"
							onclick={() => void onOpenTarget(notification)}
						>
							<span class="round-icon cyan">
								<Icon icon={notification.icon} width="18" height="18" />
							</span>
							<span>
								<strong>{notification.title}</strong>
								<small>{notification.meta} · {formatDateTime(notification.time)}</small>
								<em class:expanded={isNotificationExpanded(notification.id, $expandedNotificationIds)}>{notification.body}</em>
							</span>
						</button>
						{#if notificationNeedsExpansion(notification)}
							<button
								type="button"
								class="notification-expand"
								aria-expanded={isNotificationExpanded(notification.id, $expandedNotificationIds)}
								onclick={() => toggleNotificationExpanded(notification.id)}
							>
								{isNotificationExpanded(notification.id, $expandedNotificationIds) ? 'Show less' : 'Show full text'}
							</button>
						{/if}
						<button
							type="button"
							class="notification-dismiss"
							aria-label={`Dismiss ${notification.title}`}
							onclick={(event) => {
								event.stopPropagation();
								dismissNotification(notification.id);
							}}
						>
							<Icon icon="tabler:trash" width="16" height="16" />
						</button>
					</article>
				{/each}
			</div>
		{/if}
	</aside>
{/if}

// frontend/src/app/shell/NotificationsDrawer.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { useNotificationsDrawerSurface } from '../queries/useNotificationsDrawerSurface'

const {
  canExpandNotification,
  closeDrawer,
  formatTime,
  handleOpenTarget,
  isExpanded,
  notificationBodyPreview,
  notifications,
  t
} = useNotificationsDrawerSurface()
</script>

<template>
  <div>
    <!-- Backdrop -->
    <Transition name="drawer-backdrop">
      <div
        v-if="notifications.isNotificationsDrawerOpen"
        class="drawer-backdrop"
        @click="closeDrawer"
      />
    </Transition>

    <!-- Drawer -->
    <Transition name="drawer-slide">
      <aside
        v-if="notifications.isNotificationsDrawerOpen"
        class="notifications-drawer"
      >
        <!-- Header -->
        <div class="drawer-header">
          <div class="drawer-header-left">
            <Icon icon="tabler:bell" class="drawer-header-icon" />
            <span class="drawer-title">{{ t('notifications.title') || 'Notifications' }}</span>
            <span class="drawer-count">{{ notifications.notificationCount }}</span>
          </div>
          <button class="drawer-close-btn" @click="closeDrawer">
            <Icon icon="tabler:x" class="drawer-close-icon" />
          </button>
        </div>

        <!-- Empty State -->
        <div v-if="notifications.notificationItems.length === 0" class="drawer-empty">
          <Icon icon="tabler:bell-check" class="drawer-empty-icon" />
          <p class="drawer-empty-text">{{ t('notifications.empty') || 'All caught up!' }}</p>
        </div>

        <!-- Notification List -->
        <div v-else class="drawer-list">
          <div
            v-for="notification in notifications.notificationItems"
            :key="notification.id"
            class="notification-item"
          >
            <button
              class="notification-main"
              @click="handleOpenTarget(notification.id)"
            >
              <Icon :icon="notification.icon" class="notification-icon" />
              <div class="notification-content">
                <div class="notification-header">
                  <span class="notification-title">{{ notification.title }}</span>
                  <span class="notification-time">{{ formatTime(notification.time) }}</span>
                </div>
                <div
                  v-if="notification.body"
                  class="notification-body"
                  :class="{ expanded: isExpanded(notification.id) }"
                >
                  {{ notificationBodyPreview(notification) }}
                </div>
              </div>
            </button>
            <div class="notification-actions">
              <button
                v-if="canExpandNotification(notification)"
                class="notification-action-btn"
                @click="notifications.toggleNotificationExpanded(notification.id)"
              >
                <Icon
                  :icon="isExpanded(notification.id) ? 'tabler:chevron-up' : 'tabler:chevron-down'"
                  class="notification-action-icon"
                />
              </button>
              <button
                class="notification-action-btn"
                @click="notifications.dismissNotification(notification.id)"
              >
                <Icon icon="tabler:x" class="notification-action-icon" />
              </button>
            </div>
          </div>
        </div>
      </aside>
    </Transition>
  </div>
</template>
