// frontend/src/app/shell/Sidebar.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { useSidebarSurface } from '../queries/useSidebarSurface'

const {
  nav,
  sidebar,
  handleSelectItem,
  handleToggleGroup,
  handleToggleRail,
  handleSettings,
  isItemActive,
  isCommunicationItemActive
} = useSidebarSurface()
</script>

<template>
  <aside
    class="sidebar"
    :class="{
      'sidebar-rail': nav.isSidebarRail
    }"
  >
    <!-- Brand -->
    <div class="sidebar-brand" @click="handleSelectItem('home')">
      <div class="sidebar-logo">
        <img class="sidebar-logo-image" src="/assets/hermes-logo-mark.png" alt="" aria-hidden="true" />
      </div>
      <div v-if="!nav.isSidebarRail" class="sidebar-brand-text">
        <span class="sidebar-brand-name">Hermes</span>
        <span class="sidebar-brand-subtitle">Memory System</span>
      </div>
    </div>

    <!-- Navigation -->
    <nav class="sidebar-nav">
      <template v-for="entry in sidebar.sidebarRootEntries" :key="entry.rootId">
        <!-- Single Item -->
        <div v-if="entry.kind === 'item'" class="sidebar-nav-item-wrapper">
          <button
            class="sidebar-nav-item"
            :class="{ active: isItemActive(entry.item.itemId) }"
            @click="handleSelectItem(entry.item.itemId)"
          >
            <Icon :icon="entry.item.icon" class="sidebar-nav-icon" />
            <span v-if="!nav.isSidebarRail" class="sidebar-nav-label">
              {{ entry.item.label }}
            </span>
          </button>
        </div>

        <!-- Group -->
        <div v-else-if="entry.kind === 'group'" class="sidebar-nav-group-wrapper">
          <!-- Group Header -->
          <div v-if="!nav.isSidebarRail" class="sidebar-nav-group-header">
            <button
              class="sidebar-nav-group-toggle"
              :class="{ active: isItemActive(entry.group.id) }"
              @click="handleToggleGroup(entry.group.id)"
            >
              <Icon
                :icon="entry.group.icon"
                class="sidebar-nav-icon"
              />
              <span class="sidebar-nav-label">{{ entry.group.label }}</span>
              <Icon
                icon="tabler:chevron-down"
                class="sidebar-nav-chevron"
                :class="{ expanded: nav.expandedSidebarGroupIds.includes(entry.group.id) }"
              />
            </button>
          </div>

          <!-- Group Items (normal mode) -->
          <div
            v-if="!nav.isSidebarRail"
            class="sidebar-nav-subnav"
            :class="{ open: nav.expandedSidebarGroupIds.includes(entry.group.id) }"
          >
            <button
              v-for="item in entry.group.items"
              :key="item.itemId"
              class="sidebar-nav-item sidebar-nav-subitem"
              :class="{
                active: item.isCommunication
                  ? isCommunicationItemActive(item.sectionId)
                  : isItemActive(item.itemId)
              }"
              @click="item.isCommunication
                ? nav.navigateToCommunicationSection(item.sectionId!)
                : handleSelectItem(item.itemId)"
            >
              <Icon :icon="item.icon" class="sidebar-nav-icon" />
              <span class="sidebar-nav-label">{{ item.label }}</span>
            </button>
          </div>

          <!-- Rail mode: group shows as dropdown trigger -->
          <div v-else class="sidebar-rail-group">
            <button
              class="sidebar-nav-item"
              :class="{
                'rail-active': nav.activeSidebarRailGroupId === entry.group.id || isItemActive(entry.group.id)
              }"
              @click="nav.setActiveSidebarRailGroup(
                nav.activeSidebarRailGroupId === entry.group.id ? null : entry.group.id
              )"
            >
              <Icon :icon="entry.group.icon" class="sidebar-nav-icon" />
            </button>
            <div
              v-if="nav.activeSidebarRailGroupId === entry.group.id"
              class="sidebar-rail-dropdown"
            >
              <button
                v-for="item in entry.group.items"
                :key="item.itemId"
                class="sidebar-rail-dropdown-item"
                :class="{
                  active: item.isCommunication
                    ? isCommunicationItemActive(item.sectionId)
                    : isItemActive(item.itemId)
                }"
                @click="item.isCommunication
                  ? nav.navigateToCommunicationSection(item.sectionId!)
                  : handleSelectItem(item.itemId)"
              >
                <Icon :icon="item.icon" class="sidebar-nav-icon" />
                <span>{{ item.label }}</span>
              </button>
            </div>
          </div>
        </div>
      </template>
    </nav>

    <!-- Bottom section -->
    <div class="sidebar-footer">
      <button class="sidebar-nav-item" @click="handleToggleRail">
        <Icon
          :icon="nav.isSidebarRail ? 'tabler:layout-sidebar-right' : 'tabler:layout-sidebar'"
          class="sidebar-nav-icon"
        />
        <span v-if="!nav.isSidebarRail" class="sidebar-nav-label">
          {{ nav.isSidebarRail ? 'Expand' : 'Collapse' }}
        </span>
      </button>
      <button
        class="sidebar-nav-item"
        :class="{ active: isItemActive('settings') }"
        @click="handleSettings"
      >
        <Icon icon="tabler:settings" class="sidebar-nav-icon" />
        <span v-if="!nav.isSidebarRail" class="sidebar-nav-label">Settings</span>
      </button>
    </div>
  </aside>
</template>

// frontend/src/lib/components/shell/Sidebar.svelte
<script lang="ts">
	import './sidebar.css';
	import Icon from '@iconify/svelte';
	import { currentLocale, t } from '$lib/i18n';
	import { currentView, activeCommunicationSection, isSidebarRail, activeSidebarRailGroupId } from '$lib/stores/navigation';
	import type { ResolvedSidebarItem, ResolvedSidebarRootEntry, SidebarNavGroup, SidebarItemId, PrimaryNavId } from '$lib/layout/sidebar-navigation';

	const _ = (key: string) => t($currentLocale, key);

	type NavItem = { id: PrimaryNavId; label: string; icon: string; badge?: string; enabled: boolean };

	interface Props {
		sidebarRootEntries: ResolvedSidebarRootEntry<NavItem>[];
		expandedSidebarGroupIds: string[];
		onSelectItem: (item: ResolvedSidebarItem<NavItem>) => void;
		onToggleGroup: (group: SidebarNavGroup) => void;
		onToggleRail: () => void;
		onSettings: () => void;
	}

	let {
		sidebarRootEntries,
		expandedSidebarGroupIds,
		onSelectItem,
		onToggleGroup,
		onToggleRail,
		onSettings
	}: Props = $props();

	function sidebarGroupLabel(group: SidebarNavGroup, index: number) {
		return group.label || (group.id === 'communications' ? 'Communications' : `Group ${index + 1}`);
	}

	function sidebarItemLabel(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary' ? item.primary.label : item.section.label;
	}

	function sidebarItemIcon(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary' ? item.primary.icon : item.section.icon;
	}

	function sidebarItemBadge(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary' ? item.primary.badge : undefined;
	}

	function sidebarItemTitle(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary' && !item.primary.enabled
			? _('Not available in the current desktop scope')
			: sidebarItemLabel(item);
	}

	function isSidebarItemDisabled(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary' && !item.primary.enabled;
	}

	function isSidebarItemActive(item: ResolvedSidebarItem<NavItem>) {
		return item.kind === 'primary'
			? $currentView === item.primary.id
			: $currentView === 'communications' && $activeCommunicationSection === item.section.id;
	}

	function isSidebarGroupExpanded(groupId: string) {
		return expandedSidebarGroupIds.includes(groupId);
	}

	function sidebarGroupHasActiveItem(group: SidebarNavGroup, $cv: string, $acs: string) {
		return group.itemIds.some((itemId) => {
			const communicationSectionId = itemId.startsWith('communications.') ? itemId.replace('communications.', '') : null;
			if (communicationSectionId) {
				return $cv === 'communications' && $acs === communicationSectionId;
			}
			return $cv === itemId;
		});
	}

	function sidebarGroupHasSeparatorBefore(group: SidebarNavGroup, itemId: SidebarItemId) {
		return group.itemIds.indexOf(itemId) > 0 && group.separatorBeforeItemIds.includes(itemId);
	}
</script>

<aside class="sidebar" class:rail={$isSidebarRail} aria-label={_('Hermes Hub navigation')}>
	<div class="brand">
		<button
			type="button"
			class="brand-mark-button"
			aria-label={$isSidebarRail ? _('Expand sidebar') : _('Collapse sidebar')}
			aria-pressed={$isSidebarRail}
			title={$isSidebarRail ? _('Expand sidebar') : _('Collapse sidebar')}
			onclick={onToggleRail}
		>
			<img src="/assets/hermes-logo-mark.png" alt="" class="brand-mark" />
		</button>
		<div class="brand-copy">
			<p class="brand-name">{_('Hermes Hub')}</p>
			<p class="brand-subtitle">{_('Personal OS')}</p>
		</div>
	</div>

	<nav class="nav-group primary-nav" aria-label={_('Primary workspaces')}>
		{#each sidebarRootEntries as entry, entryIndex}
			{#if entry.kind === 'item'}
				{@const item = entry.item}
				<div class="nav-entry">
					<button
						type="button"
						class:active={isSidebarItemActive(item)}
						class:disabled={isSidebarItemDisabled(item)}
						disabled={isSidebarItemDisabled(item)}
						aria-current={isSidebarItemActive(item) ? 'page' : undefined}
						title={sidebarItemTitle(item)}
						onclick={() => onSelectItem(item)}
					>
						<Icon icon={sidebarItemIcon(item)} width="18" height="18" />
						<span>{_(sidebarItemLabel(item))}</span>
						{#if sidebarItemBadge(item)}
							<em>{sidebarItemBadge(item)}</em>
						{/if}
					</button>
				</div>
			{:else}
				{@const group = entry.group}
				<div class="nav-entry">
					<button
						type="button"
						class:active={sidebarGroupHasActiveItem(group, $currentView, $activeCommunicationSection)}
						class:has-subnav={true}
						aria-current={sidebarGroupHasActiveItem(group, $currentView, $activeCommunicationSection) ? 'page' : undefined}
						aria-expanded={$isSidebarRail ? $activeSidebarRailGroupId === group.id : isSidebarGroupExpanded(group.id)}
						aria-controls={`sidebar-group-${group.id}-sections`}
						aria-haspopup={$isSidebarRail ? 'menu' : undefined}
						title={_(sidebarGroupLabel(group, entryIndex))}
						onclick={() => onToggleGroup(group)}
					>
						<Icon icon={group.icon} width="18" height="18" />
						<span>{_(sidebarGroupLabel(group, entryIndex))}</span>
						{#if !$isSidebarRail}
							<Icon class="nav-disclosure" icon={isSidebarGroupExpanded(group.id) ? 'tabler:chevron-up' : 'tabler:chevron-down'} width="15" height="15" />
						{/if}
					</button>
					{#if $activeSidebarRailGroupId === group.id && $isSidebarRail}
						<div
							id={`sidebar-group-${group.id}-sections`}
							class="communications-rail-dropdown"
							aria-label={_('Sections')}
						>
							{#each group.items as item}
								{#if sidebarGroupHasSeparatorBefore(group, item.itemId)}
									<div class="subnav-separator" aria-hidden="true"></div>
								{/if}
								<button
									type="button"
									class="subnav-item"
									class:active={isSidebarItemActive(item)}
									aria-current={isSidebarItemActive(item) ? 'page' : undefined}
									title={sidebarItemTitle(item)}
									disabled={isSidebarItemDisabled(item)}
									onclick={() => onSelectItem(item)}
								>
									<Icon icon={sidebarItemIcon(item)} width="16" height="16" />
									<span>{_(sidebarItemLabel(item))}</span>
									{#if sidebarItemBadge(item)}
										<em>{sidebarItemBadge(item)}</em>
									{/if}
								</button>
							{/each}
						</div>
					{/if}
					{#if isSidebarGroupExpanded(group.id) && !$isSidebarRail}
						<div
							id={`sidebar-group-${group.id}-sections`}
							class="communications-subnav"
							aria-label={_('Sections')}
						>
							{#each group.items as item}
								{#if sidebarGroupHasSeparatorBefore(group, item.itemId)}
									<div class="subnav-separator" aria-hidden="true"></div>
								{/if}
								<button
									type="button"
									class="subnav-item"
									class:active={isSidebarItemActive(item)}
									aria-current={isSidebarItemActive(item) ? 'page' : undefined}
									title={sidebarItemTitle(item)}
									disabled={isSidebarItemDisabled(item)}
									onclick={() => onSelectItem(item)}
								>
									<Icon icon={sidebarItemIcon(item)} width="16" height="16" />
									<span>{_(sidebarItemLabel(item))}</span>
									{#if sidebarItemBadge(item)}
										<em>{sidebarItemBadge(item)}</em>
									{/if}
								</button>
							{/each}
						</div>
					{/if}
				</div>
			{/if}
		{/each}
	</nav>

	<div class="sidebar-tools" aria-label={_('System navigation')}>
		<button type="button" class="settings-link" class:active={$currentView === 'settings'} title={_('Open settings')} onclick={onSettings}>
			<Icon icon="tabler:settings" width="18" height="18" />
			<span>{_('Settings')}</span>
		</button>
	</div>
</aside>
