// frontend/src/lib/pages/projects/ProjectsPage.svelte
<script lang="ts">
	import { currentLocale, t } from '$lib/i18n';
	import * as projectsService from '$lib/services/projects';
	import ProjectsHero from './widgets/ProjectsHero.svelte';
	import ProjectsDashboard from './widgets/ProjectsDashboard.svelte';
	import ProjectsRail from './widgets/ProjectsRail.svelte';
	import type {
		ProjectRecord,
		ProjectStats,
		ProjectDetail,
		ProjectSummary,
		ProjectTimelineItem,
		ProjectMessageSummary,
		ProjectDocumentSummary
	} from '$lib/api';

	const _ = (key: string) => t($currentLocale, key);

	interface Props {
		isLayoutEditing: boolean;
		isWidgetVisible: (id: string) => boolean;
	}

	let { isLayoutEditing, isWidgetVisible }: Props = $props();

	let projectSummaries = $state<ProjectSummary[]>([]);
	let selectedProjectDetail = $state<ProjectDetail | null>(null);
	let selectedProjectId = $state('');
	let projectsError = $state('');
	let isProjectsLoading = $state(false);

	let selectedProjectRecord = $derived(
		selectedProjectDetail?.project ?? projectSummaries[0]?.project ?? null
	);
	let selectedProjectStats = $derived(
		selectedProjectDetail?.stats ?? projectSummaries[0]?.stats ?? projectsService.emptyProjectStats()
	);
	let relatedProjectSummaries = $derived(
		projectSummaries.filter((item) => item.project.project_id !== selectedProjectRecord?.project_id)
	);

	function projectStatusLabel(status: string) {
		return status.split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
	}

	function projectTimelineIcon(item: ProjectTimelineItem) {
		switch (item.item_kind) {
			case 'message': return 'tabler:mail';
			case 'document': return 'tabler:file-text';
			default: return 'tabler:circle-dot';
		}
	}

	function projectMessageSender(message: ProjectMessageSummary) {
		return message.sender || _('Unknown');
	}

	function projectDocumentIcon(document: ProjectDocumentSummary) {
		switch (document.document_kind) {
			case 'pdf': return 'tabler:file-type-pdf';
			case 'markdown': return 'tabler:file-text';
			default: return 'tabler:file';
		}
	}

	function formatProjectDate(value: string | null) {
		if (!value) return _('Not set');
		const date = new Date(`${value}T00:00:00`);
	if (Number.isNaN(date.getTime())) return _('Invalid date');
	return new Intl.DateTimeFormat($currentLocale ?? 'en', { month: 'short', day: 'numeric', year: 'numeric' }).format(date);
}

function formatProjectDateTime(value: string | null) {
	if (!value) return _('No activity');
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) return _('Invalid date');
	return new Intl.DateTimeFormat($currentLocale ?? 'en', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date);
	}

	function formatNumber(value: number) {
		return new Intl.NumberFormat($currentLocale ?? 'en-US').format(value);
	}

	function selectProject(item: ProjectSummary) {
		if (item.project.project_id === selectedProjectId && selectedProjectDetail) return;
		selectedProjectId = item.project.project_id;
		loadProjectDetail(item.project.project_id);
	}

	async function loadProjectDetail(projectId: string) {
		if (!projectId) { selectedProjectDetail = null; return; }
		isProjectsLoading = true;
		const result = await projectsService.loadProjectDetail(projectId);
		selectedProjectDetail = result.detail;
		projectsError = result.error;
		isProjectsLoading = false;
	}

	async function loadProjects() {
		isProjectsLoading = true;
		projectSummaries = [];
		try {
			const result = await projectsService.loadProjects(selectedProjectId, 0);
			projectSummaries = result.summaries;
			selectedProjectDetail = result.detail;
			projectsError = result.error;
			selectedProjectId = result.selectedProjectId;
		} catch (e: unknown) {
			projectsError = e instanceof Error ? e.message : _('Unknown projects error');
		}
		isProjectsLoading = false;
	}

	$effect(() => {
		loadProjects();
	});

	async function prepareAiBrief(_projectId?: string) {}
</script>

<section class="projects-page">
	<ProjectsHero
		{projectsError}
		{isProjectsLoading}
		{selectedProjectRecord}
		{selectedProjectStats}
		{projectSummaries}
		{isLayoutEditing}
		{isWidgetVisible}
		isAiMeetingPrepSubmitting={false}
		{projectStatusLabel}
		{formatProjectDate}
		{formatNumber}
		{selectProject}
		{loadProjects}
		{prepareAiBrief}
	/>

	{#if selectedProjectRecord}
		<div class="project-dashboard-grid">
			<ProjectsDashboard
				{selectedProjectDetail}
				{selectedProjectRecord}
				{selectedProjectStats}
				{isLayoutEditing}
				{isWidgetVisible}
				{projectTimelineIcon}
				{projectMessageSender}
				{projectDocumentIcon}
				{formatProjectDateTime}
				{formatNumber}
			/>
			<ProjectsRail
				{selectedProjectDetail}
				{selectedProjectRecord}
				{selectedProjectStats}
				{relatedProjectSummaries}
				{isLayoutEditing}
				{isWidgetVisible}
				{projectStatusLabel}
				{formatNumber}
			/>
		</div>
	{/if}
</section>

// frontend/src/domains/projects/views/ProjectsPage.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from '../../../platform/i18n'
import { useProjectsQuery, useProjectQuery } from '../queries/useProjectsQuery'
import { useProjectsStore } from '../stores/projects'
import ProjectsHero from '../components/ProjectsHero.vue'
import ProjectsDashboard from '../components/ProjectsDashboard.vue'
import ProjectsRail from '../components/ProjectsRail.vue'
import type { ProjectSummary, ProjectDetail } from '../types/project'

const { t } = useI18n()
const store = useProjectsStore()

const { data: projectsData, isLoading: isProjectsLoading, error: projectsErrorObj, refetch: refetchProjects } = useProjectsQuery()
const { data: projectDetailData, isLoading: isDetailLoading } = useProjectQuery(store.selectedProjectId || null)

const projectsError = computed<string>(() => {
  if (projectsErrorObj.value) return projectsErrorObj.value?.message ?? t('Unknown projects error')
  return ''
})

const projectSummaries = computed<ProjectSummary[]>(() => {
  return projectsData.value ?? []
})

const selectedProjectDetail = computed<ProjectDetail | null>(() => {
  return projectDetailData.value ?? null
})

const selectedProjectRecord = computed(() => {
  return selectedProjectDetail.value?.project ?? projectSummaries.value[0]?.project ?? null
})

const selectedProjectStats = computed(() => {
  return selectedProjectDetail.value?.stats ?? projectSummaries.value[0]?.stats ?? { message_count: 0, document_count: 0, people_count: 0, graph_connection_count: 0, latest_activity_at: null }
})

const relatedProjectSummaries = computed<ProjectSummary[]>(() => {
  const currentId = selectedProjectRecord.value?.project_id
  return projectSummaries.value.filter((item) => item.project.project_id !== currentId)
})

function selectProject(item: ProjectSummary) {
  if (item.project.project_id === store.selectedProjectId && selectedProjectDetail.value) return
  store.selectProject(item.project.project_id)
}

function loadProjects() {
  refetchProjects()
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat('en-US').format(value)
}
</script>

<template>
  <section class="projects-page">
    <ProjectsHero
      :projectsError="projectsError"
      :isProjectsLoading="isProjectsLoading"
      :selectedProjectRecord="selectedProjectRecord"
      :selectedProjectStats="selectedProjectStats"
      :projectSummaries="projectSummaries"
      :selectProject="selectProject"
      :loadProjects="loadProjects"
    />

    <div v-if="selectedProjectRecord" class="project-dashboard-grid">
      <ProjectsDashboard
        :selectedProjectDetail="selectedProjectDetail"
        :selectedProjectRecord="selectedProjectRecord"
        :selectedProjectStats="selectedProjectStats"
        :formatNumber="formatNumber"
      />
      <ProjectsRail
        :selectedProjectDetail="selectedProjectDetail"
        :selectedProjectRecord="selectedProjectRecord"
        :selectedProjectStats="selectedProjectStats"
        :relatedProjectSummaries="relatedProjectSummaries"
        :formatNumber="formatNumber"
      />
    </div>
  </section>
</template>
